import process from 'node:process'
import { fileURLToPath } from 'node:url'
import { z } from 'zod'
import { UNNAMED_BUILD } from '@molvia/model'
import model from '@/embeddings/model.json'
import { loginConfiguration } from './login-config'

// One .env at the repository root holds this working copy's ports and database,
// generated by bin/init-env.sh. It is absent in CI, where the values come from the
// environment itself.
try {
  process.loadEnvFile(fileURLToPath(new URL('../../.env', import.meta.url)))
} catch {
  // no .env in this environment — fall through to process.env
}

const envSchema = z.object({
  API_PORT: z.coerce.number().int().positive().default(3300),
  DATABASE_URL: z.string().min(1),
  NODE_ENV: z.enum(['development', 'test', 'production']).default('development'),
  /**
   * The hourly refresh of official rates (MOL-39), which goes out to the central banks. On by
   * default, so production cannot forget it; end-to-end runs switch it off, because a test that
   * depends on a foreign server answering is a test that fails for someone else's reasons.
   */
  RATES_REFRESH: z.enum(['on', 'off']).default('on'),
  /**
   * The build `/health` names (MOL-90): `git describe` of the commit the image was built from —
   * `v0.1.1-3-g1a2b3c4`, or the tag alone on a tagged commit. The image carries it; outside one it
   * is `dev`. What the deploy compares with to know the new containers are the ones answering.
   */
  APP_VERSION: z.string().min(1).default(UNNAMED_BUILD),
  /**
   * The address Open Food Facts may reach us at, sent in every request's User-Agent (MOL-162, В-4):
   * the base asks for one and may ban a client without it. Without it the hint is off — so copies,
   * CI and the tests never ask the real base; production sets it in its `.env`. Empty is unset, as
   * compose passes a variable it was not given. Printable ASCII only: it goes into a header.
   */
  OPEN_FOOD_FACTS_CONTACT: z
    .string()
    .regex(/^[\x20-\x7e]*$/)
    .optional()
    .transform((contact) => (contact === '' ? undefined : contact)),
  /**
   * The search by meaning (MOL-105): its model is loaded at boot and the writer fills the vectors.
   * On by default, so production cannot forget it; end-to-end switches it off — the search must
   * hold without it, and that run is the proof.
   */
  EMBEDDINGS: z.enum(['on', 'off']).default('on'),
  /**
   * Where the model's files are. In a working copy `.models/` beside the repository, which
   * `make model` fills; the image names its own. Files missing are not an error: the search is
   * by letters then, and the boot says so once.
   */
  EMBEDDINGS_DIR: z
    .string()
    .min(1)
    .default(fileURLToPath(new URL(`../../.models/${model.name}`, import.meta.url))),
  /** Where the base is asked; end-to-end points it at a fake of its own. */
  OPEN_FOOD_FACTS_URL: z.url({ protocol: /^https?$/ }).optional(),
  /**
   * Questions a minute to the base — end-to-end only, whose fake has no limit; production keeps
   * `OFF_PER_MINUTE`, the base's own limit less a reserve, and never sets it.
   */
  OPEN_FOOD_FACTS_PER_MINUTE: z.preprocess(
    // Empty is unset, as for the contact: `z.coerce` made it 0, and the API would not start.
    (value) => (value === '' ? undefined : value),
    z.coerce.number().int().positive().optional(),
  ),
})

export const env = envSchema.parse(process.env)
export const VERSION = env.APP_VERSION

export const loginConfig = loginConfiguration(process.env)
