import process from 'node:process'
import { fileURLToPath } from 'node:url'
import { z } from 'zod'
import { UNNAMED_BUILD, telegramUserIdSchema } from '@molvia/model'
import model from '@/embeddings/model.json'
import { loginConfiguration } from './login-config'

// One .env at the repository root holds this working copy's ports and database,
// generated by bin/init-env.sh. It is absent in CI, where the values come from the
// environment itself.
try {
  process.loadEnvFile(fileURLToPath(new URL('../../.env', import.meta.url)))
} catch {
  // no .env in this environment — fall through to process.env
}

/**
 * The owner's Telegram id as `.env.prod` writes it: digits and nothing else. One rule with Grafana's
 * `deploy/grafana/start.sh` (MOL-145, adversarial А5): read by `z.coerce`, `+123`, ` 123` and `1.23e8`
 * ran the API while the same line stopped Grafana, and every alarm with it.
 */
export const ownerTelegramIdSchema = z
  .string()
  .regex(/^\d+$/)
  .transform(Number)
  .pipe(telegramUserIdSchema)

const envSchema = z.object({
  API_PORT: z.coerce.number().int().positive().default(3300),
  /**
   * The port `/metrics` answers on (MOL-145, В-1): its own, inside the compose network, never the
   * API's — Caddy proxies only that. Unset in a copy and in end-to-end: nobody scrapes them, and no
   * port is opened. Empty is unset, as compose passes a variable it was not given.
   */
  METRICS_PORT: z.preprocess(
    (value) => (value === '' ? undefined : value),
    z.coerce.number().int().positive().optional(),
  ),
  DATABASE_URL: z.string().min(1),
  NODE_ENV: z.enum(['development', 'test', 'production']).default('development'),
  /**
   * The hourly refresh of official rates (MOL-39), which goes out to the central banks. On by
   * default, so production cannot forget it; end-to-end runs switch it off, because a test that
   * depends on a foreign server answering is a test that fails for someone else's reasons.
   */
  RATES_REFRESH: z.enum(['on', 'off']).default('on'),
  /**
   * The build `/health` names (MOL-90): `git describe` of the commit the image was built from —
   * `v0.1.1-3-g1a2b3c4`, or the tag alone on a tagged commit. The image carries it; outside one it
   * is `dev`. What the deploy compares with to know the new containers are the ones answering.
   */
  APP_VERSION: z.string().min(1).default(UNNAMED_BUILD),
  /**
   * The address Open Food Facts may reach us at, sent in every request's User-Agent (MOL-162, В-4):
   * the base asks for one and may ban a client without it. Without it the hint is off — so copies,
   * CI and the tests never ask the real base; production sets it in its `.env`. Empty is unset, as
   * compose passes a variable it was not given. Printable ASCII only: it goes into a header.
   */
  OPEN_FOOD_FACTS_CONTACT: z
    .string()
    .regex(/^[\x20-\x7e]*$/)
    .optional()
    .transform((contact) => (contact === '' ? undefined : contact)),
  /**
   * The search by meaning (MOL-105): its model is loaded at boot and the writer fills the vectors.
   * On by default, so production cannot forget it; end-to-end switches it off — the search must
   * hold without it, and that run is the proof.
   */
  EMBEDDINGS: z.enum(['on', 'off']).default('on'),
  /**
   * Where the model's files are. In a working copy `.models/` beside the repository, which
   * `make model` fills; the image names its own. Files missing are not an error: the search is
   * by letters then, and the boot says so once.
   */
  EMBEDDINGS_DIR: z
    .string()
    .min(1)
    .default(fileURLToPath(new URL(`../../.models/${model.name}`, import.meta.url))),
  /**
   * The receipt reader's address (MOL-125): `services/receipt-reader` on the compose network, a copy's
   * own on its band with `make reader`. Unset or empty, receipts are taken and wait in the queue.
   */
  RECEIPT_READER_URL: z
    .union([z.literal(''), z.url({ protocol: /^https?$/ })])
    .optional()
    .transform((url) => (url === '' ? undefined : url)),
  /**
   * Whom the bot writes about failures (MOL-143, Р-9 of MOL-149): the owner's Telegram id. Set in
   * production only — without it nothing is queued for anyone, so a copy's failures go to its table
   * and stay there. Empty is unset, as compose passes a variable it was not given.
   */
  OWNER_TELEGRAM_ID: z.preprocess(
    (value) => (value === '' ? undefined : value),
    ownerTelegramIdSchema.optional(),
  ),
  /**
   * Where the PWA is served — production's site — for `make failures` to read the phone's frames
   * through the maps published beside the build (MOL-144). Unset in a copy: its frames are the
   * development server's, already the source's.
   */
  APP_BASE_URL: z.preprocess(
    (value) => (value === '' ? undefined : value),
    z.url({ protocol: /^https?$/ }).optional(),
  ),
  /** Where the base is asked; end-to-end points it at a fake of its own. */
  OPEN_FOOD_FACTS_URL: z.url({ protocol: /^https?$/ }).optional(),
  /**
   * Questions a minute to the base — end-to-end only, whose fake has no limit; production keeps
   * `OFF_PER_MINUTE`, the base's own limit less a reserve, and never sets it.
   */
  OPEN_FOOD_FACTS_PER_MINUTE: z.preprocess(
    // Empty is unset, as for the contact: `z.coerce` made it 0, and the API would not start.
    (value) => (value === '' ? undefined : value),
    z.coerce.number().int().positive().optional(),
  ),
})

export const env = envSchema.parse(process.env)
export const VERSION = env.APP_VERSION

export const loginConfig = loginConfiguration(process.env)
