/**
 * The search corpora of MOL-5: twenty-four names, the ways a person spells them, and sixteen
 * names in three scripts. One list read twice — by the key's corpus test here, which runs
 * without a database and guards the alphabet, and by the backend's integration test, which
 * runs the same queries through the real search (MOL-13). Two copies drift silently, and
 * these already did once: `jajca` left one of them in MOL-11.
 *
 * Test data, not domain: it lives under `tests/` and reaches the backend through the
 * `./testing/search-corpus` export only — from tests, never from `src`, which the shared
 * lint preset refuses (`TEST_DATA`).
 */

export const ITEMS = [
  'Молоко Ашхар 3.2%',
  'Молоко Марианна',
  'Сыр Чанах',
  'Сыр Лори',
  'Творог',
  'Кефир',
  'Мацун',
  'Шоколад Гранд Кенди',
  'Лаваш',
  'Яйца',
  'Гречка',
  'Жигули',
  'Хумус',
  'Цукаты',
  'Йогурт',
  'Щербет',
  'Айран',
  'Джем абрикосовый',
  'Масло сливочное',
  'Чай зелёный',
  'Сахар',
  'Форель',
  'Цыплёнок',
  'Икра кабачковая',
] as const

/** What a person actually types: both halves of every fork, and typos on top of them. */
export const QUERIES: readonly (readonly [string, (typeof ITEMS)[number]])[] = [
  ['moloko', 'Молоко Ашхар 3.2%'],
  ['малако', 'Молоко Ашхар 3.2%'],
  ['malako', 'Молоко Ашхар 3.2%'],
  ['ashhar', 'Молоко Ашхар 3.2%'],
  ['ashkhar', 'Молоко Ашхар 3.2%'],
  ['chanah', 'Сыр Чанах'],
  ['chanakh', 'Сыр Чанах'],
  ['canah', 'Сыр Чанах'],
  ['чанах', 'Сыр Чанах'],
  ['tvorog', 'Творог'],
  ['kefir', 'Кефир'],
  ['matsun', 'Мацун'],
  ['macun', 'Мацун'],
  ['shokolad', 'Шоколад Гранд Кенди'],
  ['сокоlad', 'Шоколад Гранд Кенди'],
  ['chokolad', 'Шоколад Гранд Кенди'],
  ['lavash', 'Лаваш'],
  ['yaytsa', 'Яйца'],
  ['yaica', 'Яйца'],
  ['grechka', 'Гречка'],
  ['grecka', 'Гречка'],
  ['jiguli', 'Жигули'],
  ['zhiguli', 'Жигули'],
  ['humus', 'Хумус'],
  ['khumus', 'Хумус'],
  ['tsukaty', 'Цукаты'],
  ['cukati', 'Цукаты'],
  ['yogurt', 'Йогурт'],
  ['iogurt', 'Йогурт'],
  ['shcherbet', 'Щербет'],
  ['sherbet', 'Щербет'],
  ['scherbet', 'Щербет'],
  ['ayran', 'Айран'],
  ['airan', 'Айран'],
  ['djem', 'Джем абрикосовый'],
  ['jem', 'Джем абрикосовый'],
  ['maslo', 'Масло сливочное'],
  ['chai', 'Чай зелёный'],
  ['chay', 'Чай зелёный'],
  ['sahar', 'Сахар'],
  ['sakhar', 'Сахар'],
  ['forel', 'Форель'],
  ['ciplenok', 'Цыплёнок'],
  ['tsyplenok', 'Цыплёнок'],
  ['ikra', 'Икра кабачковая'],
]

/** Armenian on the shelf, Russian in the head, Latin on the keyboard. */
export const TRIPLES: readonly (readonly [string, string, string])[] = [
  ['Ջերմուկ', 'Джермук', 'Jermuk'],
  ['Չանախ', 'Чанах', 'Chanakh'],
  ['Գյումրի', 'Гюмри', 'Gyumri'],
  ['Երևան', 'Ереван', 'Yerevan'],
  ['Մածուն', 'Мацун', 'Matsun'],
  ['Լավաշ', 'Лаваш', 'Lavash'],
  ['Ղափամա', 'Гапама', 'Ghapama'],
  ['Թան', 'Тан', 'Tan'],
  ['Բասթուրմա', 'Бастурма', 'Basturma'],
  ['Քունջութ', 'Кунжут', 'Kunjut'],
  ['Աշխար', 'Ашхар', 'Ashkhar'],
  ['Նոյ', 'Ной', 'Noy'],
  ['Ծաղկունք', 'Цахкунк', 'Tsaghkunk'],
  ['Հաց', 'Ац', 'Hats'],
  ['Սուջուխ', 'Суджух', 'Sujukh'],
  ['Փախինդզ', 'Пахиндз', 'Pakhindz'],
]

/**
 * The shelf of MOL-14: sixty-four names and the words the owner actually uses for them. The
 * queries and the absent words are the owner's own, from the expense log of 25.08–18.09.2026 —
 * «кола», «дошик», «туалетка», not what a tester would type. The names are not copied from
 * receipts: the log keeps none, so they were written for the shelf of «Ереван Сити», where
 * nearly all of it was bought. Unfinished queries («мол», «прин») are cut from those words
 * and mean what the whole word means.
 *
 * A query names every item it is meant for — «молоко» both milks — so the first row is
 * right when it is any of them. Read by the backend's integration test only: the shelf
 * measures the search, not the alphabet.
 */
export const SHELF = [
  'Coca-Cola 1 л',
  'Coca-Cola 0,5 л',
  'Fanta апельсин 1 л',
  'Молоко Марианна 3,2% 1 л',
  'Молоко Ашхар 2,5% 1 л',
  'Nesquik какао-напиток 250 г',
  'Хлопья Nestlé Fitness 300 г',
  "Хлопья кукурузные Kellogg's Corn Flakes 375 г",
  'Хлеб Матнакаш',
  "Хлеб тостовый Harry's 470 г",
  'Колбаса докторская',
  'Колбаса сервелат Макур',
  'Nutella 350 г',
  'Пиво Kilikia 0,5 л',
  'Пиво Gyumri 0,5 л',
  'Говядина мякоть',
  'Фарш говяжий',
  'Сок Noy яблочный 1 л',
  'Сок Rich апельсин 1 л',
  "Чипсы Lay's сметана и лук 150 г",
  'Pringles Original 165 г',
  'Cheetos кукурузные палочки 55 г',
  'Котлеты куриные замороженные',
  'Спагетти Barilla №5 500 г',
  'Кетчуп Heinz томатный 570 г',
  'Арахис солёный 150 г',
  'Фисташки жареные 100 г',
  'Салфетки бумажные Zewa 100 шт',
  'Салфетки влажные Huggies 56 шт',
  'Картофель',
  'Виноград Арарат',
  'Нектарины',
  'Перчатки хозяйственные Vileda',
  'Батарейки Duracell AA 4 шт',
  'Белизна 1 л',
  'Кофе Jacobs Monarch молотый 230 г',
  'Креветки королевские 500 г',
  'Сливки Марианна 20% 200 мл',
  'Крекеры TUC 100 г',
  'Булочки с кунжутом 4 шт',
  'Пирожное Наполеон',
  'Вода Бжни 1,5 л',
  'Вода Джермук 0,5 л',
  'Doshirak лапша курица 90 г',
  'Паштет печёночный Hame 105 г',
  'Творог Ашхар 9% 400 г',
  'Мука пшеничная высший сорт 2 кг',
  'Туалетная бумага Zewa Plus 4 рулона',
  'Станки Gillette Blue II 5 шт',
  'Соевый соус Kikkoman 150 мл',
  'Рис длиннозёрный Мистраль 900 г',
  'Таблетки для посудомоечной машины Finish 40 шт',
  'Курица филе',
  'Курица целая охлаждённая',
  'Средство для мытья пола Mr. Proper 1 л',
  'Корм для собак Pedigree 400 г',
  'Корм для кошек Whiskas 85 г',
  'Наполнитель для кошачьего туалета 5 л',
  'Стиральный порошок Ariel 3 кг',
  'Соус чесночный Махеевъ 200 г',
  'Лапша удон 300 г',
  'Тарелка суповая',
  'Кружка керамическая',
  'Полотенце кухонное',
] as const

export const SHELF_QUERIES: readonly (readonly [string, readonly (typeof SHELF)[number][]])[] = [
  ['кола', ['Coca-Cola 1 л', 'Coca-Cola 0,5 л']],
  ['кол', ['Coca-Cola 1 л', 'Coca-Cola 0,5 л']],
  ['фанта', ['Fanta апельсин 1 л']],
  ['фан', ['Fanta апельсин 1 л']],
  ['молоко', ['Молоко Марианна 3,2% 1 л', 'Молоко Ашхар 2,5% 1 л']],
  ['мол', ['Молоко Марианна 3,2% 1 л', 'Молоко Ашхар 2,5% 1 л']],
  ['моло', ['Молоко Марианна 3,2% 1 л', 'Молоко Ашхар 2,5% 1 л']],
  ['несквик', ['Nesquik какао-напиток 250 г']],
  ['неск', ['Nesquik какао-напиток 250 г']],
  ['хлопья', ['Хлопья Nestlé Fitness 300 г', "Хлопья кукурузные Kellogg's Corn Flakes 375 г"]],
  ['хлоп', ['Хлопья Nestlé Fitness 300 г', "Хлопья кукурузные Kellogg's Corn Flakes 375 г"]],
  ['хлеб', ['Хлеб Матнакаш', "Хлеб тостовый Harry's 470 г"]],
  ['колбаса', ['Колбаса докторская', 'Колбаса сервелат Макур']],
  ['колб', ['Колбаса докторская', 'Колбаса сервелат Макур']],
  ['нутелла', ['Nutella 350 г']],
  ['нут', ['Nutella 350 г']],
  ['пиво', ['Пиво Kilikia 0,5 л', 'Пиво Gyumri 0,5 л']],
  ['говядина', ['Говядина мякоть', 'Фарш говяжий']],
  ['мясо', ['Говядина мякоть', 'Фарш говяжий']],
  ['говя', ['Говядина мякоть', 'Фарш говяжий']],
  ['сок', ['Сок Noy яблочный 1 л', 'Сок Rich апельсин 1 л']],
  ['чипсы', ["Чипсы Lay's сметана и лук 150 г", 'Pringles Original 165 г']],
  ['чип', ["Чипсы Lay's сметана и лук 150 г", 'Pringles Original 165 г']],
  ['принглс', ['Pringles Original 165 г']],
  ['прин', ['Pringles Original 165 г']],
  ['читос', ['Cheetos кукурузные палочки 55 г']],
  ['котлеты', ['Котлеты куриные замороженные']],
  ['котл', ['Котлеты куриные замороженные']],
  ['спагетти', ['Спагетти Barilla №5 500 г']],
  ['спаг', ['Спагетти Barilla №5 500 г']],
  ['кетчуп', ['Кетчуп Heinz томатный 570 г']],
  [
    'соусы',
    ['Кетчуп Heinz томатный 570 г', 'Соевый соус Kikkoman 150 мл', 'Соус чесночный Махеевъ 200 г'],
  ],
  ['орешки', ['Арахис солёный 150 г', 'Фисташки жареные 100 г']],
  ['салфетки', ['Салфетки бумажные Zewa 100 шт', 'Салфетки влажные Huggies 56 шт']],
  ['салф', ['Салфетки бумажные Zewa 100 шт', 'Салфетки влажные Huggies 56 шт']],
  ['влажные салфетки', ['Салфетки влажные Huggies 56 шт']],
  ['картошка', ['Картофель']],
  ['виноград', ['Виноград Арарат']],
  ['нектарины', ['Нектарины']],
  ['перчатки', ['Перчатки хозяйственные Vileda']],
  ['батарейки', ['Батарейки Duracell AA 4 шт']],
  ['белизна', ['Белизна 1 л']],
  ['отбеливатель', ['Белизна 1 л']],
  ['кофе', ['Кофе Jacobs Monarch молотый 230 г']],
  ['креветки', ['Креветки королевские 500 г']],
  ['сливки', ['Сливки Марианна 20% 200 мл']],
  ['крекеры', ['Крекеры TUC 100 г']],
  ['булочки', ['Булочки с кунжутом 4 шт']],
  ['булки', ['Булочки с кунжутом 4 шт']],
  ['пирожные', ['Пирожное Наполеон']],
  ['вода', ['Вода Бжни 1,5 л', 'Вода Джермук 0,5 л']],
  ['дошик', ['Doshirak лапша курица 90 г']],
  ['лапша', ['Doshirak лапша курица 90 г', 'Лапша удон 300 г']],
  ['паштет', ['Паштет печёночный Hame 105 г']],
  ['творог', ['Творог Ашхар 9% 400 г']],
  ['твор', ['Творог Ашхар 9% 400 г']],
  ['мука', ['Мука пшеничная высший сорт 2 кг']],
  ['туалетка', ['Туалетная бумага Zewa Plus 4 рулона']],
  ['бритва', ['Станки Gillette Blue II 5 шт']],
  ['соевый соус', ['Соевый соус Kikkoman 150 мл']],
  ['рис', ['Рис длиннозёрный Мистраль 900 г']],
  ['таблетки для посудомойки', ['Таблетки для посудомоечной машины Finish 40 шт']],
  ['курица', ['Курица филе', 'Курица целая охлаждённая']],
  ['кур', ['Курица филе', 'Курица целая охлаждённая']],
  ['средство для полов', ['Средство для мытья пола Mr. Proper 1 л']],
  ['собачий корм', ['Корм для собак Pedigree 400 г']],
  ['корм', ['Корм для собак Pedigree 400 г', 'Корм для кошек Whiskas 85 г']],
  ['наполнитель', ['Наполнитель для кошачьего туалета 5 л']],
  ['стиральный порошок', ['Стиральный порошок Ariel 3 кг']],
  ['порошок', ['Стиральный порошок Ariel 3 кг']],
  ['тарелки', ['Тарелка суповая']],
  ['кружки', ['Кружка керамическая']],
  ['полотенца', ['Полотенце кухонное']],
]

/** Words from the same log for what the shelf does not carry: a search should find nothing. */
export const SHELF_ABSENT: readonly string[] = [
  'пельмени',
  'хинкали',
  'игрушка',
  'прищепки',
  'подставка в душ',
  'лоток',
  'мышки',
  'эластичный бинт',
  'пончики',
  'роллы',
  'мохито',
  'синтезатор',
  'симка',
  'цветы',
  'духи',
  'лимонад',
  'шницель',
  'овощи',
  'специи',
]

/**
 * Not the owner's words — the adversarial pass's (MOL-14): fifty everyday purchases the shelf
 * does not carry. The owner's nineteen absent words find something twice; these, at the same
 * thresholds, find something in about half — a taste printed on another item («сметана» is
 * in the chips' name), a unit word («шт»), the absolute budget. Pinned as they are.
 */
export const SHELF_EVERYDAY_ABSENT: readonly string[] = [
  'яйца',
  'сахар',
  'соль',
  'масло',
  'чай',
  'сыр',
  'кефир',
  'йогурт',
  'бананы',
  'яблоки',
  'апельсины',
  'томаты',
  'помидоры',
  'чеснок',
  'кукуруза',
  'печень',
  'лук',
  'сметана',
  'сосиски',
  'макароны',
  'гречка',
  'огурцы',
  'зелень',
  'суп',
  'ложка',
  'лезвия',
  'щётка',
  'зубная паста',
  'шампунь',
  'мыло',
  'губка',
  'пакеты',
  'фольга',
  'плов',
  'шаурма',
  'тоник',
  'сироп',
  'вино',
  'коньяк',
  'водка',
  'сигареты',
  'жвачка',
  'шоколад',
  'конфеты',
  'мороженое',
  'торт',
  'пирог',
  'сухарики',
  'семечки',
  'печенье',
]

/**
 * The same shelf typed another way — not the owner's words either: Latin, as a keyboard
 * without Cyrillic types it, and Latin brands spelled in Cyrillic («хаггис», «лейс»).
 */
export const SHELF_TYPED_OTHERWISE: readonly (readonly [string, readonly string[]])[] = [
  ['kola', ['Coca-Cola 1 л', 'Coca-Cola 0,5 л']],
  ['cola', ['Coca-Cola 1 л', 'Coca-Cola 0,5 л']],
  ['coca cola', ['Coca-Cola 1 л', 'Coca-Cola 0,5 л']],
  ['moloko', ['Молоко Марианна 3,2% 1 л', 'Молоко Ашхар 2,5% 1 л']],
  ['pivo', ['Пиво Kilikia 0,5 л', 'Пиво Gyumri 0,5 л']],
  ['hleb', ['Хлеб Матнакаш', "Хлеб тостовый Harry's 470 г"]],
  ['jacobs', ['Кофе Jacobs Monarch молотый 230 г']],
  ['gyumri', ['Пиво Gyumri 0,5 л']],
  ['kilikia', ['Пиво Kilikia 0,5 л']],
  ['zewa', ['Салфетки бумажные Zewa 100 шт', 'Туалетная бумага Zewa Plus 4 рулона']],
  ['ariel', ['Стиральный порошок Ariel 3 кг']],
  ['finish', ['Таблетки для посудомоечной машины Finish 40 шт']],
  ['pedigree', ['Корм для собак Pedigree 400 г']],
  ['duracell', ['Батарейки Duracell AA 4 шт']],
  ['gillette', ['Станки Gillette Blue II 5 шт']],
  ['mr proper', ['Средство для мытья пола Mr. Proper 1 л']],
  ['хаггис', ['Салфетки влажные Huggies 56 шт']],
  ['лейс', ["Чипсы Lay's сметана и лук 150 г"]],
]

/** Armenian labels on the same shelf, and how a Russian or Latin keyboard reaches them. */
export const SHELF_ARMENIAN = [
  'Մածուն Մարիաննա',
  'Ջերմուկ',
  'Պանիր Լոռի',
  'Լավաշ',
  'Թան Բժնի',
  'Հաց Մատնաքաշ',
  'Թթվասեր Աշխարհ',
] as const

export const SHELF_ARMENIAN_QUERIES: readonly (readonly [string, readonly string[]])[] = [
  ['мацун', ['Մածուն Մարիաննա']],
  ['matsun', ['Մածուն Մարիաննա']],
  ['джермук', ['Ջերմուկ', 'Вода Джермук 0,5 л']],
  ['jermuk', ['Ջերմուկ', 'Вода Джермук 0,5 л']],
  ['лори', ['Պանիր Լոռի']],
  ['lori', ['Պանիր Լոռի']],
  ['лаваш', ['Լավաշ']],
  ['lavash', ['Լավաշ']],
  ['тан', ['Թան Բժնի']],
  ['tan', ['Թան Բժնի']],
  ['бжни', ['Թան Բժնի', 'Вода Бжни 1,5 л']],
  ['матнакаш', ['Հաց Մատնաքաշ', 'Хлеб Матнакаш']],
  ['ашхар', ['Թթվասեր Աշխարհ', 'Молоко Ашхар 2,5% 1 л', 'Творог Ашхар 9% 400 г']],
]
