import { describe, expect, it } from 'vitest'
import am01 from './receipt-text.am-01.json'
import am03 from './receipt-text.am-03.json'
import am04 from './receipt-text.am-04.json'
import am05 from './receipt-text.am-05.json'
import { bestReading, mergeParts, parseReceiptText, rowsOf } from '#model/entities/receipt-text'
import type { ReceiptText } from '#model/entities/receipt-text'

/**
 * The fixtures are the owner's receipts as Tesseract read them on the server (MOL-114) — the item
 * rows and the total line only, under a made-up header (В-7): the repository is public. `expected` is
 * what the prototype (`hybrid.mjs` of the bench) gave on the same text, in its own floats; the port
 * must give it line for line. Regenerated by `.scratch/tasks/status/MOL-125/fixtures.mjs`.
 */
interface Fixture {
  readings: string[]
  expected: {
    tin: string | null
    date: string | null
    time: string | null
    receiptNo: string | null
    total: number | null
    balanced: boolean
    lines: {
      printed: string
      hs: string
      sku?: string
      qty: number | null
      unit: 'kg' | 'pcs'
      unit_price: number | null
      sum: number | null
      discount: number | null
      settled: boolean
    }[]
  }
}

const hundredths = (x: number | null) => (x === null ? null : Math.round(x * 100))
const thousandths = (x: number | null) => (x === null ? null : Math.round(x * 1000))

function read(fixture: Fixture): ReceiptText {
  return bestReading(fixture.readings.map((text) => rowsOf(text, 0)))
}

describe('a receipt read by Tesseract, as the prototype read it', () => {
  it.each([
    ['am-01', am01],
    ['am-03', am03],
    ['am-04', am04],
    ['am-05', am05],
  ] as [string, Fixture][])('%s', (_, fixture) => {
    const got = read(fixture)
    const want = fixture.expected
    expect({
      tin: got.tin,
      date: got.date,
      time: got.time,
      receiptNo: got.receiptNo,
      total: got.totalHundredths,
      balanced: got.balanced,
    }).toEqual({
      tin: want.tin,
      date: want.date,
      time: want.time,
      receiptNo: want.receiptNo,
      total: hundredths(want.total),
      balanced: want.balanced,
    })
    expect(
      got.lines.map((l) => [
        l.printed,
        l.hs,
        l.sku,
        l.quantityMilli,
        l.unit,
        l.priceHundredths,
        l.sumHundredths,
        l.discountHundredths,
        l.settled,
      ]),
    ).toEqual(
      want.lines.map((l) => [
        l.printed,
        l.hs,
        l.sku ?? null,
        thousandths(l.qty),
        l.unit === 'kg' ? 'kg' : 'piece',
        hundredths(l.unit_price),
        hundredths(l.sum),
        hundredths(l.discount),
        l.settled,
      ]),
    )
  })

  it('reads the card layout with the till discount and the weight: am-03, 17 of 18 lines', () => {
    const got = read(am03 as Fixture)
    expect(got.layout).toBe('card')
    expect(got.lines).toHaveLength(17)
    // «1602/9001487 1,3124q 4013,64/40,64 Յ090» — «կգ» read as «4q», «3» as «Յ»: 1,312 kg × 3 090
    const pork = got.lines[4]!
    expect([pork.quantityMilli, pork.unit, pork.priceHundredths, pork.sumHundredths]).toEqual([
      1312,
      'kg',
      309_000,
      401_354,
    ])
  })

  it('reads the table layout of Dog City and lets the total decide: am-04', () => {
    const got = read(am04 as Fixture)
    expect(got.layout).toBe('table')
    expect(got.totalHundredths).toBe(945_000)
    expect(got.lines.reduce((sum, l) => sum + (l.sumHundredths ?? 0), 0)).toBe(945_000)
  })

  it('settles a receipt with no card discount by its total: am-05 adds up', () => {
    const got = read(am05 as Fixture)
    expect(got.balanced).toBe(true)
    expect(got.lines.reduce((sum, l) => sum + (l.sumHundredths ?? 0), 0)).toBe(got.totalHundredths)
  })

  it('cuts a line out by its name and figures when the number of the item was read', () => {
    const coke = read(am03 as Fixture).lines[1]!
    expect(coke.rows.map((r) => r.text)).toEqual([
      '2.Գազավորված ըմպելիք «Կոկա Կոլա» 1.6լ',
      '2202/096796 14տ 702,9/7,1 710',
    ])
  })

  it('cuts only the figures when the number was not read — «Յ» for «3»', () => {
    const milk = read(am03 as Fixture).lines[2]!
    expect(milk.rows.map((r) => r.text)).toEqual(['0401/1163909 1Հտ 366,3/3,7 370'])
  })

  it('cuts only the heading row of a table', () => {
    const got = read(am04 as Fixture)
    expect(
      got.lines.every((line) => line.rows.length === 1 && /\(\d{4}\)/.test(line.rows[0]!.text)),
    ).toBe(true)
  })
})

describe('what is never cut out (review, MOL-125)', () => {
  it('a row of the head above the first item whose name OCR lost: a buyer, the VAT', () => {
    const text = [
      'Որից ԱԱՀ = 1 446,36',
      'Գնորդ՝ Իվան Պետրով, հեռ. 091 123456',
      '3923/1122223 1Հտ 60 60',
      '2.Կաթ «Իգիթ» 3.2% 1լ',
      '0401/1163909 2Հտ 740 370',
    ].join('\n')
    const lines = parseReceiptText(rowsOf(text, 0)).lines
    expect(lines.map((l) => l.rows.map((r) => r.text))).toEqual([
      ['3923/1122223 1Հտ 60 60'],
      ['2.Կաթ «Իգիթ» 3.2% 1լ', '0401/1163909 2Հտ 740 370'],
    ])
  })
})

describe('a reading OCR glued into long figures', () => {
  // twelve lines whose every field is long digits OCR confuses: the search grows as a power of them
  const glued = (digits: number, count = 12) =>
    Array.from({ length: count }, (_, i) =>
      [
        `${String(i + 1)}.Կաթ`,
        `0401/1163909 1Հտ ${'5'.repeat(digits)},56/${'6'.repeat(digits)},65 ${'8'.repeat(digits)}`,
      ].join('\n'),
    ).join('\n')

  it.each([6, 9, 12, 20])('is laid out in under two seconds with %i-digit figures', (digits) => {
    const started = performance.now()
    const got = parseReceiptText(rowsOf(glued(digits), 0))
    expect(got.lines).toHaveLength(12)
    expect(performance.now() - started).toBeLessThan(2_000)
  })
})

describe('what is not a receipt', () => {
  it('finds no lines in no text', () => {
    const got = parseReceiptText(rowsOf('', 0))
    expect([got.lines, got.totalHundredths, got.balanced, got.tin]).toEqual([[], null, false, null])
  })

  it('finds no lines in text with no figures', () => {
    expect(parseReceiptText(rowsOf('ԵՐԵՎԱՆ-ՍԻԹԻ\nՇնորհակալություն', 0)).lines).toEqual([])
  })

  it('refuses no readings at all', () => {
    expect(() => bestReading([])).toThrow(RangeError)
  })
})

describe('the figures of one line', () => {
  const receipt = (figures: string, total?: string) =>
    parseReceiptText(
      rowsOf(
        ['1.Կաթ «Իգիթ» 3.2% 1լ', figures, ...(total ? [`Ընդամենը ${total}`] : [])].join('\n'),
        0,
      ),
    )

  it('undoes a digit swapped by OCR by the arithmetic of the line: 850 read as 860', () => {
    const line = receipt('0401/1163909 1Հտ 760,75/89,25 860').lines[0]!
    expect([
      line.priceHundredths,
      line.sumHundredths,
      line.discountHundredths,
      line.settled,
    ]).toEqual([85_000, 76_075, 8_925, true])
  })

  it('splits paid and shelf price with no discount: 2 × 370', () => {
    const line = receipt('0401/1163909 2Հտ 740 370').lines[0]!
    expect([line.quantityMilli, line.priceHundredths, line.sumHundredths]).toEqual([
      2_000, 37_000, 74_000,
    ])
  })

  it('lets the total decide between two readings that both add up: «60 60» or «50 50»', () => {
    const asRead = receipt('3923/1122223 1Հտ 60 60').lines[0]!
    const byTotal = receipt('3923/1122223 1Հտ 60 60', '50.00')
    expect(asRead.sumHundredths).toBe(6_000)
    expect([byTotal.balanced, byTotal.lines[0]!.sumHundredths]).toEqual([true, 5_000])
  })

  it('leaves a line no arithmetic holds unsettled, with the figures as printed', () => {
    const line = receipt('0401/1163909 1Հտ 100,50/1,50 999').lines[0]!
    expect([line.settled, line.sumHundredths]).toEqual([false, 10_050])
  })
})

describe('parts of a long receipt', () => {
  const part = (index: number, ...rows: string[]) => rowsOf(rows.join('\n'), index)

  it('joins at the last article both parts have, dropping the overlap', () => {
    const merged = mergeParts([
      part(0, '1.Կաթ', '0401/1163909 1Հտ 370 370', '2.Հաց', '1905/1100001 1Հտ 250 250'),
      part(1, '2.Հաց', '1905/1100001 1Հտ 250 250', '3.Ձու', '0407/1100002 1Հտ 90 90'),
    ])
    expect(merged.map((r) => [r.part, r.line].join(':'))).toEqual([
      '0:0',
      '0:1',
      '0:2',
      '0:3',
      '1:2',
      '1:3',
    ])
  })

  it('finds the seam with one digit of the article misread', () => {
    const merged = mergeParts([
      part(0, '1905/1100001 1Հտ 250 250'),
      part(1, '1905/1100004 1Հտ 250 250', '0407/1100002 1Հտ 90 90'),
    ])
    expect(merged.map((r) => r.text)).toEqual([
      '1905/1100001 1Հտ 250 250',
      '0407/1100002 1Հտ 90 90',
    ])
  })

  it('puts parts with no common article one after another', () => {
    const merged = mergeParts([part(0, 'a'), part(1, 'b'), part(2, 'c')])
    expect(merged.map((r) => r.text)).toEqual(['a', 'b', 'c'])
  })
})
