import { describe, expect, it } from 'vitest'
import am01 from './receipt-text.am-01.json'
import am03 from './receipt-text.am-03.json'
import am04 from './receipt-text.am-04.json'
import am05 from './receipt-text.am-05.json'
import { needsReshoot } from '#model/entities/receipt'
import { bestReading, mergeParts, parseReceiptText, rowsOf } from '#model/entities/receipt-text'
import type { ReceiptText, TextRow } from '#model/entities/receipt-text'

/**
 * The fixtures are the owner's receipts as Tesseract read them on the server (MOL-114) — the item
 * rows and the total line only, under a made-up header (В-7): the repository is public. `expected` is
 * what the prototype (`hybrid.mjs` of the bench) gave on the same text, in its own floats; the port
 * must give it line for line. Regenerated by `.scratch/tasks/status/MOL-125/fixtures.mjs`.
 */
interface Fixture {
  readings: string[]
  expected: {
    tin: string | null
    date: string | null
    time: string | null
    receiptNo: string | null
    total: number | null
    balanced: boolean
    lines: {
      printed: string
      hs: string
      sku?: string
      qty: number | null
      unit: 'kg' | 'pcs'
      unit_price: number | null
      sum: number | null
      discount: number | null
      settled: boolean
    }[]
  }
}

const hundredths = (x: number | null) => (x === null ? null : Math.round(x * 100))
const thousandths = (x: number | null) => (x === null ? null : Math.round(x * 1000))

function read(fixture: Fixture): ReceiptText {
  return bestReading(fixture.readings.map((text) => rowsOf(text, 0)))
}

describe('a receipt read by Tesseract, as the prototype read it', () => {
  it.each([
    ['am-01', am01],
    ['am-03', am03],
    ['am-04', am04],
    ['am-05', am05],
  ] as [string, Fixture][])('%s', (_, fixture) => {
    const got = read(fixture)
    const want = fixture.expected
    expect({
      tin: got.tin,
      date: got.date,
      time: got.time,
      receiptNo: got.receiptNo,
      total: got.totalHundredths,
      balanced: got.balanced,
    }).toEqual({
      tin: want.tin,
      date: want.date,
      time: want.time,
      receiptNo: want.receiptNo,
      total: hundredths(want.total),
      balanced: want.balanced,
    })
    expect(
      got.lines.map((l) => [
        l.printed,
        l.hs,
        l.sku,
        l.quantityMilli,
        l.unit,
        l.priceHundredths,
        l.sumHundredths,
        l.discountHundredths,
        l.settled,
      ]),
    ).toEqual(
      want.lines.map((l) => [
        l.printed,
        l.hs,
        l.sku ?? null,
        thousandths(l.qty),
        l.unit === 'kg' ? 'kg' : 'piece',
        hundredths(l.unit_price),
        hundredths(l.sum),
        hundredths(l.discount),
        l.settled,
      ]),
    )
  })

  it('reads the card layout with the till discount and the weight: am-03, 17 of 18 lines', () => {
    const got = read(am03 as Fixture)
    expect(got.layout).toBe('card')
    expect(got.lines).toHaveLength(17)
    // «1602/9001487 1,3124q 4013,64/40,64 Յ090» — «կգ» read as «4q», «3» as «Յ»: 1,312 kg × 3 090
    const pork = got.lines[4]!
    expect([pork.quantityMilli, pork.unit, pork.priceHundredths, pork.sumHundredths]).toEqual([
      1312,
      'kg',
      309_000,
      401_354,
    ])
  })

  it('reads the table layout of Dog City and lets the total decide: am-04', () => {
    const got = read(am04 as Fixture)
    expect(got.layout).toBe('table')
    expect(got.totalHundredths).toBe(945_000)
    expect(got.lines.reduce((sum, l) => sum + (l.sumHundredths ?? 0), 0)).toBe(945_000)
  })

  it('settles a receipt with no card discount by its total: am-05 adds up', () => {
    const got = read(am05 as Fixture)
    expect(got.balanced).toBe(true)
    expect(got.lines.reduce((sum, l) => sum + (l.sumHundredths ?? 0), 0)).toBe(got.totalHundredths)
  })

  it('cuts a line out by its name and figures when the number of the item was read', () => {
    const coke = read(am03 as Fixture).lines[1]!
    expect(coke.rows.map((r) => r.text)).toEqual([
      '2.Գազավորված ըմպելիք «Կոկա Կոլա» 1.6լ',
      '2202/096796 14տ 702,9/7,1 710',
    ])
  })

  it('cuts only the figures when the number was not read — «Յ» for «3»', () => {
    const milk = read(am03 as Fixture).lines[2]!
    expect(milk.rows.map((r) => r.text)).toEqual(['0401/1163909 1Հտ 366,3/3,7 370'])
  })

  it('cuts only the heading row of a table', () => {
    const got = read(am04 as Fixture)
    expect(
      got.lines.every((line) => line.rows.length === 1 && /\(\d{4}\)/.test(line.rows[0]!.text)),
    ).toBe(true)
  })
})

describe('what is never cut out (review, MOL-125)', () => {
  it('a row of the head above the first item whose name OCR lost: a buyer, the VAT', () => {
    const text = [
      'Որից ԱԱՀ = 1 446,36',
      'Գնորդ՝ Իվան Պետրով, հեռ. 091 123456',
      '3923/1122223 1Հտ 60 60',
      '2.Կաթ «Իգիթ» 3.2% 1լ',
      '0401/1163909 2Հտ 740 370',
    ].join('\n')
    const lines = parseReceiptText(rowsOf(text, 0)).lines
    expect(lines.map((l) => l.rows.map((r) => r.text))).toEqual([
      ['3923/1122223 1Հտ 60 60'],
      ['2.Կաթ «Իգիթ» 3.2% 1լ', '0401/1163909 2Հտ 740 370'],
    ])
  })
})

describe('a reading OCR glued into long figures', () => {
  // twelve lines whose every field is long digits OCR confuses: the search grows as a power of them
  const glued = (digits: number, count = 12) =>
    Array.from({ length: count }, (_, i) =>
      [
        `${String(i + 1)}.Կաթ`,
        `0401/1163909 1Հտ ${'5'.repeat(digits)},56/${'6'.repeat(digits)},65 ${'8'.repeat(digits)}`,
      ].join('\n'),
    ).join('\n')

  it.each([6, 9, 12, 20])(
    'is laid out in seconds, not minutes, with %i-digit figures',
    (digits) => {
      const started = performance.now()
      const got = parseReceiptText(rowsOf(glued(digits), 0))
      expect(got.lines).toHaveLength(12)
      expect(performance.now() - started).toBeLessThan(5_000)
    },
  )
})

describe('what is not a receipt', () => {
  it('finds no lines in no text', () => {
    const got = parseReceiptText(rowsOf('', 0))
    expect([got.lines, got.totalHundredths, got.balanced, got.tin]).toEqual([[], null, false, null])
  })

  it('finds no lines in text with no figures', () => {
    expect(parseReceiptText(rowsOf('ԵՐԵՎԱՆ-ՍԻԹԻ\nՇնորհակալություն', 0)).lines).toEqual([])
  })

  it('refuses no readings at all', () => {
    expect(() => bestReading([])).toThrow(RangeError)
  })
})

describe('the figures of one line', () => {
  const receipt = (figures: string, total?: string) =>
    parseReceiptText(
      rowsOf(
        ['1.Կաթ «Իգիթ» 3.2% 1լ', figures, ...(total ? [`Ընդամենը ${total}`] : [])].join('\n'),
        0,
      ),
    )

  it('undoes a digit swapped by OCR by the arithmetic of the line: 850 read as 860', () => {
    const line = receipt('0401/1163909 1Հտ 760,75/89,25 860').lines[0]!
    expect([
      line.priceHundredths,
      line.sumHundredths,
      line.discountHundredths,
      line.settled,
    ]).toEqual([85_000, 76_075, 8_925, true])
  })

  it('splits paid and shelf price with no discount: 2 × 370', () => {
    const line = receipt('0401/1163909 2Հտ 740 370').lines[0]!
    expect([line.quantityMilli, line.priceHundredths, line.sumHundredths]).toEqual([
      2_000, 37_000, 74_000,
    ])
  })

  it('lets the total decide between two readings that both add up: «60 60» or «50 50»', () => {
    const asRead = receipt('3923/1122223 1Հտ 60 60').lines[0]!
    const byTotal = receipt('3923/1122223 1Հտ 60 60', '50.00')
    expect(asRead.sumHundredths).toBe(6_000)
    expect([byTotal.balanced, byTotal.lines[0]!.sumHundredths]).toEqual([true, 5_000])
  })

  it('leaves a line no arithmetic holds unsettled, with the figures as printed', () => {
    const line = receipt('0401/1163909 1Հտ 100,50/1,50 999').lines[0]!
    expect([line.settled, line.sumHundredths]).toEqual([false, 10_050])
  })
})

describe('parts of a long receipt', () => {
  const part = (index: number, ...rows: string[]) => rowsOf(rows.join('\n'), index)

  it('joins at the last article both parts have, dropping the overlap', () => {
    const merged = mergeParts([
      part(0, '1.Կաթ', '0401/1163909 1Հտ 370 370', '2.Հաց', '1905/1100001 1Հտ 250 250'),
      part(1, '2.Հաց', '1905/1100001 1Հտ 250 250', '3.Ձու', '0407/1100002 1Հտ 90 90'),
    ])
    expect(merged.map((r) => [r.part, r.line].join(':'))).toEqual([
      '0:0',
      '0:1',
      '0:2',
      '0:3',
      '1:2',
      '1:3',
    ])
  })

  it('finds the seam with one digit of the article misread', () => {
    const merged = mergeParts([
      part(0, '1905/1100001 1Հտ 250 250'),
      part(1, '1905/1100004 1Հտ 250 250', '0407/1100002 1Հտ 90 90'),
    ])
    expect(merged.map((r) => r.text)).toEqual([
      '1905/1100001 1Հտ 250 250',
      '0407/1100002 1Հտ 90 90',
    ])
  })

  it('puts parts with no common article one after another', () => {
    const merged = mergeParts([part(0, 'a'), part(1, 'b'), part(2, 'c')])
    expect(merged.map((r) => r.text)).toEqual(['a', 'b', 'c'])
  })
})

// Review rounds 1–2 of MOL-125: what the adversarial review proved, held here so it stays fixed.
const parse = (text: string): ReceiptText => parseReceiptText(rowsOf(text, 0))
const money = (h: number) => `${String(Math.floor(h / 100))},${String(h % 100).padStart(2, '0')}`
const totalRow = (h: number) =>
  `Ընդամենը ${String(Math.floor(h / 100))}.${String(h % 100).padStart(2, '0')}`

describe('a till that prints no shelf price, settled against its total (review Р14)', () => {
  // am-01's till: «paid/discount», a tenth off every line — every swap of a line «fits» the line
  const receipt = (count: number) => {
    let seed = 7
    const rnd = (n: number) => {
      seed = (seed * 1103515245 + 12345) % 2147483648
      return seed % n
    }
    let total = 0
    const body = Array.from({ length: count }, (_, i) => {
      const paid = 20_000 + rnd(200_000)
      total += paid
      return `${String(i + 1)}. item\n0401/1163${String(100 + i)} 1Հտ ${money(paid)}/${money(Math.round(paid * 0.105))}`
    })
    return [...body, totalRow(total)].join('\n')
  }

  it.each([12, 18, 30])('balances %i lines in seconds, not minutes', (count) => {
    const started = performance.now()
    const got = parse(receipt(count))
    expect([got.lines.length, got.balanced]).toEqual([count, true])
    expect(performance.now() - started).toBeLessThan(5_000)
  })
})

describe('rows of an item’s shape above the list (review Р15)', () => {
  // a stamp or a smudge read as items: each under a line's ceiling, together over the reading's
  const junk = (ones: number, k: number) =>
    `${String(k)}. x\n0401/1163${String(k)}0 1 ${'1'.repeat(ones)},11/${'1'.repeat(ones)}`

  it('leave every real line its search: am-05’s yoghurt still reads 290,00, settled', () => {
    const text = (am05 as Fixture).readings[0]!.replace(
      'Որից ԱԱՀ = 1 446,36',
      ['Որից ԱԱՀ = 1 446,36', junk(23, 7), junk(23, 8), junk(19, 9)].join('\n'),
    )
    const yoghurt = parse(text).lines.find((line) => line.sku === '1160033')!
    expect([yoghurt.sumHundredths, yoghurt.settled]).toEqual([29_000, true])
  })
})

describe('a line printed with no discount among discounted ones (review Р5)', () => {
  it('keeps the zero it printed rather than the receipt’s rate', () => {
    const got = parse(
      [
        '1. Կաթ',
        '0401/1163909 1Հտ 99,1/0,9 100',
        '2. Հաց',
        '1905/1078044 1Հտ 99,1/0,9 100',
        '3. Գինի',
        '2204/1234567 1Հտ 1000,00/0,0 1000',
        totalRow(119_820),
      ].join('\n'),
    )
    const wine = got.lines[2]!
    expect([wine.sumHundredths, wine.discountHundredths, wine.priceHundredths]).toEqual([
      100_000, 0, 100_000,
    ])
  })
})

describe('a receipt barely read (review Р6)', () => {
  const crumpled = [
    '1. Կաթ',
    '0401/1163909 1Հտ 99,1/0,9 100',
    '2. Ինչ-որ բան',
    '0402/1163901 1Հտ 13,13/13,13 2',
    totalRow(1_000_000),
  ].join('\n')

  it('gives a line with no reading nothing of the total when the lines do not meet it', () => {
    const got = parse(crumpled)
    expect(got.balanced).toBe(false)
    expect(got.lines[1]!.sumHundredths).not.toBe(990_090)
  })

  it('is «переснимите»', () => {
    expect(needsReshoot(parse(crumpled))).toBe(true)
  })
})

describe('the head is never a name row to cut, though it starts with digits (review Р16)', () => {
  it.each(['01.10.2026 12:00 Գանձապահ՝ Աննա Սարգսյան', '091 123456 Իվան Պետրով'])('%s', (head) => {
    const lines = parse([head, '3923/1122223 1Հտ 60 60'].join('\n')).lines
    expect(lines[0]!.rows.map((r) => r.text)).toEqual(['3923/1122223 1Հտ 60 60'])
  })
})

describe('the seam of two parts (review Р7–Р9)', () => {
  const part = (index: number, ...rows: string[]): TextRow[] => rowsOf(rows.join('\n'), index)
  const articles = (rows: readonly TextRow[]) =>
    rows.flatMap((r) => /\d{4}\s*\/\s*(\d{5,})/.exec(r.text)?.[1] ?? [])

  it('is no other item’s near article: an overlap of a name row only joins the parts', () => {
    const merged = mergeParts([
      part(0, '1. Կեֆիր', '0401/1163909 1Հտ 366,3/3,7 370', '2. Հաց'),
      part(
        1,
        '2. Հաց',
        '1905/1078044 1Հտ 247,5/2,5 250',
        '3. Պանիր',
        '0406/1163903 1Հտ 1 980,0/20 2000',
      ),
    ])
    expect(articles(merged)).toEqual(['1163909', '1078044', '1163903'])
    expect(merged.filter((r) => r.text === '2. Հաց')).toHaveLength(1)
  })

  it('is not the first of two bags', () => {
    const merged = mergeParts([
      part(
        0,
        '1. Տոպրակ',
        '3923/1122223 1Հտ 49,6/0,4 50',
        '2. Կեֆիր',
        '0401/1163909 1Հտ 366,3/3,7 370',
        '3. Տոպրակ',
      ),
      part(
        1,
        '3. Տոպրակ',
        '3923/1122223 1Հտ 49,6/0,4 50',
        '4. Կարագ',
        '0405/1234567 1Հտ 891,0/9 900',
      ),
    ])
    expect(articles(merged)).toEqual(['1122223', '1163909', '1122223', '1234567'])
  })

  it('keeps every line of an overlap of two items with near articles once', () => {
    const merged = mergeParts([
      part(
        0,
        '1. Կաթ',
        '0401/1163903 1Հտ 366,3/3,7 370',
        '2. Կեֆիր',
        '0401/1163909 1Հտ 445,5/4,5 450',
      ),
      part(
        1,
        '1. Կաթ',
        '0401/1163903 1Հտ 366,3/3,7 370',
        '2. Կեֆիր',
        '0401/1163909 1Հտ 445,5/4,5 450',
        '3. Կարագ',
        '0405/1234567 1Հտ 891,0/9 900',
      ),
    ])
    expect(articles(merged)).toEqual(['1163903', '1163909', '1234567'])
  })
})

// Review round 3 of MOL-125.
describe('a long receipt whose overlap the second part read worse (review Р17)', () => {
  // am-05 shot in two parts, overlapping on items 9 and 10
  const rows = (am05 as Fixture).readings[0]!.split('\n')
  const firstEnd = rows.findIndex((row) => row.startsWith('0809/016189'))
  const secondStart = rows.findIndex((row) => row.startsWith('9.Յոգուրտ'))
  const joined = (edit: (row: string) => string) =>
    parseReceiptText(
      mergeParts([
        rowsOf(rows.slice(0, firstEnd + 1).join('\n'), 0),
        rowsOf(rows.slice(secondStart).map(edit).join('\n'), 1),
      ]),
    )
  const whole = parse((am05 as Fixture).readings[0]!)
  const skus = (r: ReceiptText) => r.lines.map((line) => line.sku)

  it.each([
    ['an article two digits off', (row: string) => row.replace('0809/016189', '0809/046139')],
    [
      'figures cut at its top edge',
      (row: string) => row.replace('0809/016189 0,694q 342,66 386', '0809/01'),
    ],
  ])('%s: the lines of the whole reading, the overlap as the first part read it', (_, edit) => {
    const got = joined(edit)
    expect(skus(got)).toEqual(skus(whole))
    expect(got.lines.map((line) => line.sumHundredths)).toEqual(
      whole.lines.map((line) => line.sumHundredths),
    )
  })
})

describe('rows of junk by the hundred (review Р18)', () => {
  const junk = (n: number) =>
    Array.from(
      { length: n },
      (_, i) =>
        `${String((i % 90) + 1)}. x\n0401/11${String(60_000 + i)} 1 ${'1'.repeat(9)},11/${'1'.repeat(9)}`,
    ).join('\n')

  it('are searched only as far as the budgets go: the rest is taken as read', () => {
    // each row tries ~7 500: the reading's 300 000 and the floors' 200 000 settle at most ~70 of
    // them, whatever their number — the work, not a clock, is what the test can hold on any machine
    const started = performance.now()
    const got = parse(`${junk(400)}\n${totalRow(1_000_000)}`)
    expect(got.lines).toHaveLength(400)
    expect(got.lines.filter((line) => line.settled).length).toBeLessThan(100)
    // and against a fall back to seconds a row, with room for a slow runner
    expect(performance.now() - started).toBeLessThan(5_000)
  })
})

describe('the name row of the first item, which has the head above it (review Р19)', () => {
  it('is never cut out, whatever stray digit OCR read at the edge', () => {
    const text = [
      '1 Գնորդ՝ Իվան Պետրով, հեռ. 091 123456',
      '3923/1122223 1Հտ 60 60',
      '2.Կաթ',
      '0401/1163909 2Հտ 740 370',
    ].join('\n')
    const lines = parse(text).lines
    expect(lines.map((l) => l.rows.map((r) => r.text))).toEqual([
      ['3923/1122223 1Հտ 60 60'],
      ['2.Կաթ', '0401/1163909 2Հտ 740 370'],
    ])
  })
})

describe('the beam keeps the reading the total asks for (review П11)', () => {
  it('thirty lines with confused digits in two of them: every sum put right', () => {
    let seed = 7
    const rnd = (k: number) => {
      seed = (seed * 1103515245 + 12345) % 2147483648
      return seed % k
    }
    const swap: Record<string, string> = { 5: '6', 6: '5', 3: '8', 1: '4' }
    let total = 0
    const truth: number[] = []
    const body = Array.from({ length: 30 }, (_, i) => {
      const paid = 20_000 + rnd(200_000)
      total += paid
      truth.push(paid)
      let printed = money(paid)
      if (i === 4 || i === 20) {
        const k = Array.from(printed).findIndex((c) => c in swap)
        if (k >= 0)
          printed = printed.slice(0, k) + (swap[printed.charAt(k)] ?? '') + printed.slice(k + 1)
      }
      return `${String(i + 1)}. item\n0401/1163${String(100 + i)} 1Հտ ${printed}/${money(Math.round(paid * 0.105))}`
    })
    const got = parse([...body, totalRow(total)].join('\n'))
    expect(got.balanced).toBe(true)
    expect(got.lines.map((line) => line.sumHundredths)).toEqual(truth)
  })
})
