import { describe, expect, it } from 'vitest'
import am01 from './receipt-text.am-01.json'
import am03 from './receipt-text.am-03.json'
import am04 from './receipt-text.am-04.json'
import am05 from './receipt-text.am-05.json'
import am14 from './receipt-text.am-14.json'
import am14t from './receipt-text.am-14t.json'
import { moneyOfHundredths, needsReshoot, receiptLineOf } from '#model/entities/receipt'
import { readPartly } from '#model/entities/receipt-sum'
import {
  bestReading,
  likeness,
  mergeParts,
  parseReceiptText,
  rowsOf,
} from '#model/entities/receipt-text'
import type { ReceiptText, TextRow } from '#model/entities/receipt-text'

/**
 * The fixtures are the owner's receipts as Tesseract read them on the server (MOL-114) — the item
 * rows and the total line only, under a made-up header (В-7): the repository is public. `expected` is
 * what the prototype (`hybrid.mjs` of the bench) gave on the same text, in its own floats; the port
 * must give it line for line. Regenerated by `.scratch/tasks/status/MOL-125/fixtures.mjs`.
 */
interface Fixture {
  readings: string[]
  expected: {
    tin: string | null
    date: string | null
    time: string | null
    receiptNo: string | null
    total: number | null
    balanced: boolean
    lines: {
      printed: string
      hs: string
      sku?: string
      qty: number | null
      unit: 'kg' | 'pcs'
      unit_price: number | null
      sum: number | null
      discount: number | null
      settled: boolean
    }[]
  }
}

const hundredths = (x: number | null) => (x === null ? null : Math.round(x * 100))
const thousandths = (x: number | null) => (x === null ? null : Math.round(x * 1000))

// Where the port departs from the prototype on purpose: a line the total changed from its reading is
// highlighted (review Р27) — am-05's peaches, 342,66 read and 342,65 by the total, right but not as read.
const CHANGED_BY_TOTAL: Readonly<Record<string, readonly string[]>> = { 'am-05': ['016189'] }

function read(fixture: Fixture): ReceiptText {
  return bestReading(fixture.readings.map((text) => rowsOf(text, 0)))
}

describe('a receipt read by Tesseract, as the prototype read it', () => {
  it.each([
    ['am-01', am01],
    ['am-03', am03],
    ['am-04', am04],
    ['am-05', am05],
  ] as [string, Fixture][])('%s', (name, fixture) => {
    const got = read(fixture)
    const want = fixture.expected
    expect({
      tin: got.tin,
      date: got.date,
      time: got.time,
      receiptNo: got.receiptNo,
      total: got.totalHundredths,
      balanced: got.balanced,
    }).toEqual({
      tin: want.tin,
      date: want.date,
      time: want.time,
      receiptNo: want.receiptNo,
      total: hundredths(want.total),
      balanced: want.balanced,
    })
    expect(
      got.lines.map((l) => [
        l.printed,
        l.hs,
        l.sku,
        l.quantityMilli,
        l.unit,
        l.priceHundredths,
        l.sumHundredths,
        l.discountHundredths,
        l.settled,
      ]),
    ).toEqual(
      want.lines.map((l) => [
        l.printed,
        l.hs,
        l.sku ?? null,
        thousandths(l.qty),
        l.unit === 'kg' ? 'kg' : 'piece',
        hundredths(l.unit_price),
        hundredths(l.sum),
        hundredths(l.discount),
        l.settled && !(CHANGED_BY_TOTAL[name] ?? []).includes(l.sku ?? ''),
      ]),
    )
  })

  it('reads the card layout with the till discount and the weight: am-03, 17 of 18 lines', () => {
    const got = read(am03 as Fixture)
    expect(got.layout).toBe('card')
    expect(got.lines).toHaveLength(17)
    // «1602/9001487 1,3124q 4013,64/40,64 Յ090» — «կգ» read as «4q», «3» as «Յ»: 1,312 kg × 3 090
    const pork = got.lines[4]!
    expect([pork.quantityMilli, pork.unit, pork.priceHundredths, pork.sumHundredths]).toEqual([
      1312,
      'kg',
      309_000,
      401_354,
    ])
  })

  it('reads the table layout of Dog City and lets the total decide: am-04', () => {
    const got = read(am04 as Fixture)
    expect(got.layout).toBe('table')
    expect(got.totalHundredths).toBe(945_000)
    expect(got.lines.reduce((sum, l) => sum + (l.sumHundredths ?? 0), 0)).toBe(945_000)
  })

  it('settles a receipt with no card discount by its total: am-05 adds up', () => {
    const got = read(am05 as Fixture)
    expect(got.balanced).toBe(true)
    expect(got.lines.reduce((sum, l) => sum + (l.sumHundredths ?? 0), 0)).toBe(got.totalHundredths)
  })

  it('cuts a line out by its name and figures when the number of the item was read', () => {
    const coke = read(am03 as Fixture).lines[1]!
    expect(coke.rows.map((r) => r.text)).toEqual([
      '2.Գազավորված ըմպելիք «Կոկա Կոլա» 1.6լ',
      '2202/096796 14տ 702,9/7,1 710',
    ])
  })

  it('cuts only the figures when the number was not read — «Յ» for «3»', () => {
    const milk = read(am03 as Fixture).lines[2]!
    expect(milk.rows.map((r) => r.text)).toEqual(['0401/1163909 1Հտ 366,3/3,7 370'])
  })

  it('cuts only the heading row of a table', () => {
    const got = read(am04 as Fixture)
    expect(
      got.lines.every((line) => line.rows.length === 1 && /\(\d{4}\)/.test(line.rows[0]!.text)),
    ).toBe(true)
  })
})

describe('what is never cut out (review, MOL-125)', () => {
  it('a row of the head above the first item whose name OCR lost: a buyer, the VAT', () => {
    const text = [
      'Որից ԱԱՀ = 1 446,36',
      'Գնորդ՝ Իվան Պետրով, հեռ. 091 123456',
      '3923/1122223 1Հտ 60 60',
      '2.Կաթ «Իգիթ» 3.2% 1լ',
      '0401/1163909 2Հտ 740 370',
    ].join('\n')
    const lines = parseReceiptText(rowsOf(text, 0)).lines
    expect(lines.map((l) => l.rows.map((r) => r.text))).toEqual([
      ['3923/1122223 1Հտ 60 60'],
      ['2.Կաթ «Իգիթ» 3.2% 1լ', '0401/1163909 2Հտ 740 370'],
    ])
  })
})

describe('a reading OCR glued into long figures', () => {
  // twelve lines whose every field is long digits OCR confuses: the search grows as a power of them
  const glued = (digits: number, count = 12) =>
    Array.from({ length: count }, (_, i) =>
      [
        `${String(i + 1)}.Կաթ`,
        `0401/1163909 1Հտ ${'5'.repeat(digits)},56/${'6'.repeat(digits)},65 ${'8'.repeat(digits)}`,
      ].join('\n'),
    ).join('\n')

  it.each([6, 9, 12, 20])(
    'is laid out in seconds, not minutes, with %i-digit figures',
    (digits) => {
      const started = performance.now()
      const got = parseReceiptText(rowsOf(glued(digits), 0))
      expect(got.lines).toHaveLength(12)
      expect(performance.now() - started).toBeLessThan(5_000)
    },
  )
})

describe('what is not a receipt', () => {
  it('finds no lines in no text', () => {
    const got = parseReceiptText(rowsOf('', 0))
    expect([got.lines, got.totalHundredths, got.balanced, got.tin]).toEqual([[], null, false, null])
  })

  it('finds no lines in text with no figures', () => {
    expect(parseReceiptText(rowsOf('ԵՐԵՎԱՆ-ՍԻԹԻ\nՇնորհակալություն', 0)).lines).toEqual([])
  })

  it('refuses no readings at all', () => {
    expect(() => bestReading([])).toThrow(RangeError)
  })
})

describe('the figures of one line', () => {
  const receipt = (figures: string, total?: string) =>
    parseReceiptText(
      rowsOf(
        ['1.Կաթ «Իգիթ» 3.2% 1լ', figures, ...(total ? [`Ընդամենը ${total}`] : [])].join('\n'),
        0,
      ),
    )

  it('undoes a digit swapped by OCR by the arithmetic of the line: 850 read as 860', () => {
    const line = receipt('0401/1163909 1Հտ 760,75/89,25 860').lines[0]!
    expect([
      line.priceHundredths,
      line.sumHundredths,
      line.discountHundredths,
      line.settled,
    ]).toEqual([85_000, 76_075, 8_925, true])
  })

  it('splits paid and shelf price with no discount: 2 × 370', () => {
    const line = receipt('0401/1163909 2Հտ 740 370').lines[0]!
    expect([line.quantityMilli, line.priceHundredths, line.sumHundredths]).toEqual([
      2_000, 37_000, 74_000,
    ])
  })

  it('lets the total decide between two readings that both add up: «60 60» or «50 50»', () => {
    const asRead = receipt('3923/1122223 1Հտ 60 60').lines[0]!
    const byTotal = receipt('3923/1122223 1Հտ 60 60', '50.00')
    expect(asRead.sumHundredths).toBe(6_000)
    expect([byTotal.balanced, byTotal.lines[0]!.sumHundredths]).toEqual([true, 5_000])
  })

  it('leaves a line no arithmetic holds unsettled, with the figures as printed', () => {
    const line = receipt('0401/1163909 1Հտ 100,50/1,50 999').lines[0]!
    expect([line.settled, line.sumHundredths]).toEqual([false, 10_050])
  })
})

describe('parts of a long receipt', () => {
  const part = (index: number, ...rows: string[]) => rowsOf(rows.join('\n'), index)

  it('joins at the last article both parts have, dropping the overlap', () => {
    const merged = mergeParts([
      part(0, '1.Կաթ', '0401/1163909 1Հտ 370 370', '2.Հաց', '1905/1100001 1Հտ 250 250'),
      part(1, '2.Հաց', '1905/1100001 1Հտ 250 250', '3.Ձու', '0407/1100002 1Հտ 90 90'),
    ])
    expect(merged.map((r) => [r.part, r.line].join(':'))).toEqual([
      '0:0',
      '0:1',
      '0:2',
      '0:3',
      '1:2',
      '1:3',
    ])
  })

  it('finds the seam with one digit of the article misread', () => {
    const merged = mergeParts([
      part(0, '1905/1100001 1Հտ 250 250'),
      part(1, '1905/1100004 1Հտ 250 250', '0407/1100002 1Հտ 90 90'),
    ])
    expect(merged.map((r) => r.text)).toEqual([
      '1905/1100001 1Հտ 250 250',
      '0407/1100002 1Հտ 90 90',
    ])
  })

  it('puts parts with no common article one after another', () => {
    const merged = mergeParts([part(0, 'a'), part(1, 'b'), part(2, 'c')])
    expect(merged.map((r) => r.text)).toEqual(['a', 'b', 'c'])
  })
})

// Review rounds 1–2 of MOL-125: what the adversarial review proved, held here so it stays fixed.
const parse = (text: string): ReceiptText => parseReceiptText(rowsOf(text, 0))
const money = (h: number) => `${String(Math.floor(h / 100))},${String(h % 100).padStart(2, '0')}`
const totalRow = (h: number) =>
  `Ընդամենը ${String(Math.floor(h / 100))}.${String(h % 100).padStart(2, '0')}`

describe('a till that prints no shelf price, settled against its total (review Р14)', () => {
  // am-01's till: «paid/discount», a tenth off every line — every swap of a line «fits» the line
  const receipt = (count: number) => {
    let seed = 7
    const rnd = (n: number) => {
      seed = (seed * 1103515245 + 12345) % 2147483648
      return seed % n
    }
    let total = 0
    const body = Array.from({ length: count }, (_, i) => {
      const paid = 20_000 + rnd(200_000)
      total += paid
      return `${String(i + 1)}. item\n0401/1163${String(100 + i)} 1Հտ ${money(paid)}/${money(Math.round(paid * 0.105))}`
    })
    return [...body, totalRow(total)].join('\n')
  }

  it.each([12, 18, 30])('balances %i lines in seconds, not minutes', (count) => {
    const started = performance.now()
    const got = parse(receipt(count))
    expect([got.lines.length, got.balanced]).toEqual([count, true])
    expect(performance.now() - started).toBeLessThan(5_000)
  })
})

describe('rows of an item’s shape above the list (review Р15)', () => {
  // a stamp or a smudge read as items: each under a line's ceiling, together over the reading's
  const junk = (ones: number, k: number) =>
    `${String(k)}. x\n0401/1163${String(k)}0 1 ${'1'.repeat(ones)},11/${'1'.repeat(ones)}`

  it('leave every real line its search: am-05’s yoghurt still reads 290,00, settled', () => {
    const text = (am05 as Fixture).readings[0]!.replace(
      'Որից ԱԱՀ = 1 446,36',
      ['Որից ԱԱՀ = 1 446,36', junk(23, 7), junk(23, 8), junk(19, 9)].join('\n'),
    )
    const yoghurt = parse(text).lines.find((line) => line.sku === '1160033')!
    expect([yoghurt.sumHundredths, yoghurt.settled]).toEqual([29_000, true])
  })
})

describe('a line printed with no discount among discounted ones (review Р5)', () => {
  it('keeps the zero it printed rather than the receipt’s rate', () => {
    const got = parse(
      [
        '1. Կաթ',
        '0401/1163909 1Հտ 99,1/0,9 100',
        '2. Հաց',
        '1905/1078044 1Հտ 99,1/0,9 100',
        '3. Գինի',
        '2204/1234567 1Հտ 1000,00/0,0 1000',
        totalRow(119_820),
      ].join('\n'),
    )
    const wine = got.lines[2]!
    expect([wine.sumHundredths, wine.discountHundredths, wine.priceHundredths]).toEqual([
      100_000, 0, 100_000,
    ])
  })
})

describe('a receipt barely read (review Р6)', () => {
  const crumpled = [
    '1. Կաթ',
    '0401/1163909 1Հտ 99,1/0,9 100',
    '2. Ինչ-որ բան',
    '0402/1163901 1Հտ 13,13/13,13 2',
    totalRow(1_000_000),
  ].join('\n')

  it('gives a line with no reading nothing of the total when the lines do not meet it', () => {
    const got = parse(crumpled)
    expect(got.balanced).toBe(false)
    expect(got.lines[1]!.sumHundredths).not.toBe(990_090)
  })

  it('is read in part, not «переснимите»: its lines go to the review (MOL-222, В-1)', () => {
    const got = parse(crumpled)
    expect(needsReshoot(got)).toBe(false)
    const lines = got.lines.map((line) => receiptLineOf(line, 'AMD'))
    expect(readPartly(lines, moneyOfHundredths(got.totalHundredths, 'AMD'))).toBe(true)
  })
})

describe('the head is never a name row to cut, though it starts with digits (review Р16)', () => {
  it.each(['01.10.2026 12:00 Գանձապահ՝ Աննա Սարգսյան', '091 123456 Իվան Պետրով'])('%s', (head) => {
    const lines = parse([head, '3923/1122223 1Հտ 60 60'].join('\n')).lines
    expect(lines[0]!.rows.map((r) => r.text)).toEqual(['3923/1122223 1Հտ 60 60'])
  })
})

describe('the seam of two parts (review Р7–Р9)', () => {
  const part = (index: number, ...rows: string[]): TextRow[] => rowsOf(rows.join('\n'), index)
  const articles = (rows: readonly TextRow[]) =>
    rows.flatMap((r) => /\d{4}\s*\/\s*(\d{5,})/.exec(r.text)?.[1] ?? [])

  it('is no other item’s near article: an overlap of a name row only joins the parts', () => {
    const merged = mergeParts([
      part(0, '1. Կեֆիր', '0401/1163909 1Հտ 366,3/3,7 370', '2. Հաց'),
      part(
        1,
        '2. Հաց',
        '1905/1078044 1Հտ 247,5/2,5 250',
        '3. Պանիր',
        '0406/1163903 1Հտ 1 980,0/20 2000',
      ),
    ])
    expect(articles(merged)).toEqual(['1163909', '1078044', '1163903'])
    expect(merged.filter((r) => r.text === '2. Հաց')).toHaveLength(1)
  })

  it('is not the first of two bags', () => {
    const merged = mergeParts([
      part(
        0,
        '1. Տոպրակ',
        '3923/1122223 1Հտ 49,6/0,4 50',
        '2. Կեֆիր',
        '0401/1163909 1Հտ 366,3/3,7 370',
        '3. Տոպրակ',
      ),
      part(
        1,
        '3. Տոպրակ',
        '3923/1122223 1Հտ 49,6/0,4 50',
        '4. Կարագ',
        '0405/1234567 1Հտ 891,0/9 900',
      ),
    ])
    expect(articles(merged)).toEqual(['1122223', '1163909', '1122223', '1234567'])
  })

  it('keeps every line of an overlap of two items with near articles once', () => {
    const merged = mergeParts([
      part(
        0,
        '1. Կաթ',
        '0401/1163903 1Հտ 366,3/3,7 370',
        '2. Կեֆիր',
        '0401/1163909 1Հտ 445,5/4,5 450',
      ),
      part(
        1,
        '1. Կաթ',
        '0401/1163903 1Հտ 366,3/3,7 370',
        '2. Կեֆիր',
        '0401/1163909 1Հտ 445,5/4,5 450',
        '3. Կարագ',
        '0405/1234567 1Հտ 891,0/9 900',
      ),
    ])
    expect(articles(merged)).toEqual(['1163903', '1163909', '1234567'])
  })
})

// Review round 3 of MOL-125.
describe('a long receipt whose overlap the second part read worse (review Р17)', () => {
  // am-05 shot in two parts, overlapping on items 9 and 10
  const rows = (am05 as Fixture).readings[0]!.split('\n')
  const firstEnd = rows.findIndex((row) => row.startsWith('0809/016189'))
  const secondStart = rows.findIndex((row) => row.startsWith('9.Յոգուրտ'))
  const joined = (edit: (row: string) => string) =>
    parseReceiptText(
      mergeParts([
        rowsOf(rows.slice(0, firstEnd + 1).join('\n'), 0),
        rowsOf(rows.slice(secondStart).map(edit).join('\n'), 1),
      ]),
    )
  const whole = parse((am05 as Fixture).readings[0]!)
  const skus = (r: ReceiptText) => r.lines.map((line) => line.sku)

  it.each([
    ['an article two digits off', (row: string) => row.replace('0809/016189', '0809/046139')],
    [
      'figures cut at its top edge',
      (row: string) => row.replace('0809/016189 0,694q 342,66 386', '0809/01'),
    ],
  ])('%s: the lines of the whole reading, the overlap as the first part read it', (_, edit) => {
    const got = joined(edit)
    expect(skus(got)).toEqual(skus(whole))
    expect(got.lines.map((line) => line.sumHundredths)).toEqual(
      whole.lines.map((line) => line.sumHundredths),
    )
  })
})

describe('rows of junk by the hundred (review Р18)', () => {
  const junk = (n: number) =>
    Array.from(
      { length: n },
      (_, i) =>
        `${String((i % 90) + 1)}. x\n0401/11${String(60_000 + i)} 1 ${'1'.repeat(9)},11/${'1'.repeat(9)}`,
    ).join('\n')

  it('are searched only as far as the budgets go: the rest is taken as read', () => {
    // each row tries ~7 500: the reading's 300 000 and the floors' 200 000 settle at most ~70 of
    // them, whatever their number — the work, not a clock, is what the test can hold on any machine
    const started = performance.now()
    const got = parse(`${junk(400)}\n${totalRow(1_000_000)}`)
    expect(got.lines).toHaveLength(400)
    expect(got.lines.filter((line) => line.settled).length).toBeLessThan(100)
    // and against a fall back to seconds a row, with room for a slow runner
    expect(performance.now() - started).toBeLessThan(5_000)
  })
})

describe('the name row of the first item, which has the head above it (review Р19)', () => {
  it('is never cut out, whatever stray digit OCR read at the edge', () => {
    const text = [
      '1 Գնորդ՝ Իվան Պետրով, հեռ. 091 123456',
      '3923/1122223 1Հտ 60 60',
      '2.Կաթ',
      '0401/1163909 2Հտ 740 370',
    ].join('\n')
    const lines = parse(text).lines
    expect(lines.map((l) => l.rows.map((r) => r.text))).toEqual([
      ['3923/1122223 1Հտ 60 60'],
      ['2.Կաթ', '0401/1163909 2Հտ 740 370'],
    ])
  })
})

describe('the beam keeps the reading the total asks for (review П11)', () => {
  it('thirty lines with confused digits in two of them: every sum put right', () => {
    let seed = 7
    const rnd = (k: number) => {
      seed = (seed * 1103515245 + 12345) % 2147483648
      return seed % k
    }
    const swap: Record<string, string> = { 5: '6', 6: '5', 3: '8', 1: '4' }
    let total = 0
    const truth: number[] = []
    const body = Array.from({ length: 30 }, (_, i) => {
      const paid = 20_000 + rnd(200_000)
      total += paid
      truth.push(paid)
      let printed = money(paid)
      if (i === 4 || i === 20) {
        const k = Array.from(printed).findIndex((c) => c in swap)
        if (k >= 0)
          printed = printed.slice(0, k) + (swap[printed.charAt(k)] ?? '') + printed.slice(k + 1)
      }
      return `${String(i + 1)}. item\n0401/1163${String(100 + i)} 1Հտ ${printed}/${money(Math.round(paid * 0.105))}`
    })
    const got = parse([...body, totalRow(total)].join('\n'))
    expect(got.balanced).toBe(true)
    expect(got.lines.map((line) => line.sumHundredths)).toEqual(truth)
  })
})

// Review round 4 of MOL-125.
describe('two fixes of one digit the total cannot tell apart (review Р20)', () => {
  const lines = (figures: readonly string[], total: string) =>
    parse(
      [
        ...figures.map((f, i) => `${String(i + 1)}. item\n0401/116300${String(i)} 1Հտ ${f}`),
        `Ընդամենը ${total}`,
      ].join('\n'),
    )

  it('the rate the lines share chooses: 816,32 read as 316,32 is put right, not another line', () => {
    const got = lines(
      [
        '2197,44/230,73',
        '1430,72/150,23',
        '1146,56/120,39',
        '316,32/85,71',
        '344,00/36,12',
        '248,00/26,04',
        '1517,76/159,36',
        '1186,88/124,62',
        '1856,96/194,98',
        '1359,68/142,77',
      ],
      '12104.32',
    )
    expect(got.balanced).toBe(true)
    expect([got.lines[3]!.sumHundredths, got.lines[9]!.sumHundredths]).toEqual([81_632, 135_968])
  })

  it('where nothing chooses — a swap in the tens of luma — the line the total changed is not vouched for', () => {
    // 1 000,55 read as 1 000,65; 3 000,60 read right: «6 → 5» in either line meets the total
    const got = lines(['1000,65/105,00', '2000,00/210,00', '3000,60/315,00'], '6001.15')
    expect(got.balanced).toBe(true)
    expect(got.lines.some((line) => !line.settled)).toBe(true)
  })
})

describe('the seam with two blemishes in the overlap, or a cut row at the first part’s foot (review Р21, 9)', () => {
  const rows = (am05 as Fixture).readings[0]!.split('\n')
  const first = rows.slice(0, rows.findIndex((row) => row.startsWith('0809/016189')) + 1).join('\n')
  const second = rows
    .slice(rows.findIndex((row) => row.startsWith('9.Յոգուրտ')))
    .map((row) => row.replace('0809/016189', '0809/046139'))
  const joined = (part2: readonly string[]) =>
    parseReceiptText(mergeParts([rowsOf(first, 0), rowsOf(part2.join('\n'), 1)]))
  const whole = parse((am05 as Fixture).readings[0]!).lines.map((line) => line.sku)

  it('item 10’s name lost at the next part’s top edge as well', () => {
    expect(
      joined(second.filter((row) => !row.startsWith('10,Դեղձ'))).lines.map((l) => l.sku),
    ).toEqual(whole)
  })

  it('item 10’s name split into two rows there', () => {
    const split = second.flatMap((row) =>
      row.startsWith('10,Դեղձ') ? ['10,Դեղձ', '(հայկական) կգ'] : [row],
    )
    expect(joined(split).lines.map((l) => l.sku)).toEqual(whole)
  })

  it('a row cut through at the first part’s foot takes no name from the next part', () => {
    const got = parseReceiptText(
      mergeParts([
        rowsOf(
          [
            '1.Կաթ',
            '0401/1163909 2Հտ 740 370',
            '2.Հաց սպիտակ',
            '1905/1234567 1Հտ 300 300',
            '~—— .,.',
          ].join('\n'),
          0,
        ),
        rowsOf(
          [
            '0401/1163909 2Հտ 740 370',
            '2.Հաց սպիտակ',
            '1905/1299967 1Հտ 300 300',
            '3.Պանիր Լոռի',
            '0406/7654321 1Հտ 2100 2100',
          ].join('\n'),
          1,
        ),
      ]),
    )
    expect(got.lines.map((line) => line.printed)).toEqual(['Կաթ', 'Հաց սպիտակ', 'Պանիր Լոռի'])
  })
})

describe('rows of a thousand letters after the articles (review Р22)', () => {
  // the work, not the clock (review 12): a row is compared by its first eighty letters only
  it('are compared by their first eighty letters', () => {
    const head = 'Կաթ«Մարիան»3,2%1լ'.repeat(6).slice(0, 80)
    expect(likeness(`${head}${'Ա'.repeat(920)}`, `${head}${'Բ'.repeat(920)}`)).toBe(1)
    expect(
      likeness(`${head.slice(1)}Ա${'Ա'.repeat(920)}`, `${head}${'Ա'.repeat(920)}`),
    ).toBeLessThan(1)
  })

  it('cost a seam no more than its first eighty letters', () => {
    let seed = 1
    const letter = () => {
      seed = (seed * 1103515245 + 12345) % 2147483648
      return 'ԱԲԳԴԵԶԷԸ'.charAt((seed >> 16) % 8)
    }
    const long = () => Array.from({ length: 700 }, letter).join('')
    const articles = Array.from({ length: 200 }, (_, i) => `0401/${String(1_100_000 + i * 37)}`)
    const part1 = [...articles.map((a) => `${a} x\n${long()}`), '0401/9999999 x'].join('\n')
    const part2 = articles.map((a) => `${a} x\n${long()}`).join('\n')
    const started = performance.now()
    mergeParts([rowsOf(part1, 0), rowsOf(part2, 1)])
    // a backstop as loose as its neighbours': CI's machine is slower than any laptop
    expect(performance.now() - started).toBeLessThan(5_000)
  })
})

// Review round 5 of MOL-125.
describe('a line of a till with no shelf price whose figures OCR glued long (review 10)', () => {
  it('is laid out with its neighbours, ninety thousand readings of it and no throw', () => {
    const glued = `${'3568'.repeat(5)},38/${'3568'.repeat(5)},85`
    const text = [
      ...Array.from(
        { length: 5 },
        (_, i) => `${String(i + 1)}.Հաց\n1905/116300${String(i)} 1Հտ 300,00/0`,
      ),
      `6.x\n1905/1163009 1Հտ ${glued}`,
    ].join('\n')
    const got = parse(text)
    expect(got.lines).toHaveLength(6)
    expect(got.lines.slice(0, 5).map((line) => line.sumHundredths)).toEqual(
      Array.from({ length: 5 }, () => 30_000),
    )
  })
})

describe('two flavours of one yoghurt, numbered in a row (review Р23)', () => {
  const rows = (am05 as Fixture).readings[0]!.split('\n')
  const at = (start: string) => rows.findIndex((row) => row.startsWith(start))
  const twoParts = (firstEndsAt: string, secondStartsAt: string, edit = (r: string[]) => r) =>
    parseReceiptText(
      mergeParts([
        rowsOf(rows.slice(0, at(firstEndsAt) + 1).join('\n'), 0),
        rowsOf(edit(rows.slice(at(secondStartsAt))).join('\n'), 1),
      ]),
    )
  const whole = parse((am05 as Fixture).readings[0]!).lines.map((line) => line.sku)

  it('are two items when the parts are cut between them with no overlap', () => {
    expect(twoParts('0403/1160033', '9.Յոգուրտ').lines.map((l) => l.sku)).toEqual(whole)
  })

  it('are two items when the overlap ends in the first and the second part lost it at its edge', () => {
    const got = twoParts('0403/1160033', '7.Պոլիէթիլենային', (r) =>
      r
        .filter((row) => !row.startsWith('8.Յոգուրտ'))
        .map((row) => (row.startsWith('0403/1160033') ? '0403/11' : row)),
    )
    expect(got.lines.map((l) => l.sku)).toEqual(whole)
  })
})

describe('a tie of a till with no discount (review Р24)', () => {
  it('highlights the line OCR misread as well as the line the total changed', () => {
    const figures = [
      '2197,44',
      '1430,72',
      '1146,56',
      '316,32',
      '344,00',
      '248,00',
      '1517,76',
      '1186,88',
      '1856,96',
      '1359,68',
    ]
    const got = parse(
      [
        ...figures.map((f, i) => `${String(i + 1)}. item\n0401/116300${String(i)} 1Հտ ${f}/0,00`),
        'Ընդամենը 12104.32',
      ].join('\n'),
    )
    expect(got.balanced).toBe(true)
    const doubtful = got.lines.flatMap((line, i) => (line.settled ? [] : [i]))
    expect(doubtful).toEqual(expect.arrayContaining([3, 9]))
  })
})

// Review round 6 of MOL-125.
describe('neighbours of one line numbered …5 and …6, one swap of OCR apart (review Р25)', () => {
  const rows = (am05 as Fixture).readings[0]!.replace('0403/1160033', '0403/1160035').split('\n')
  const at = (start: string) => rows.findIndex((row) => row.startsWith(start))
  const twoParts = (secondStartsAt: string, edit = (r: string[]) => r) =>
    parseReceiptText(
      mergeParts([
        rowsOf(rows.slice(0, at('0403/1160035') + 1).join('\n'), 0),
        rowsOf(edit(rows.slice(at(secondStartsAt))).join('\n'), 1),
      ]),
    )
  const whole = parse(rows.join('\n')).lines.map((line) => line.sku)

  it('are two items when the parts are cut between them with no overlap', () => {
    expect(twoParts('9.Յոգուրտ').lines.map((l) => l.sku)).toEqual(whole)
  })

  it('are two items when the second part lost the first of them at its edge', () => {
    const got = twoParts('7.Պոլիէթիլենային', (r) =>
      r
        .filter((row) => !row.startsWith('8.Յոգուրտ'))
        .map((row) => (row.startsWith('0403/1160035') ? '0403/11' : row)),
    )
    expect(got.lines.map((l) => l.sku)).toEqual(whole)
  })
})

describe('a rule under the head and a rule above the total, with no overlap between the parts (review 11)', () => {
  it('joins the parts and loses no item', () => {
    const rule = '------------------------------'
    const got = parseReceiptText(
      mergeParts([
        rowsOf(
          [
            'ՎԱՃԱՌՔ',
            rule,
            '1.Կաթ',
            '0401/1163909 2Հտ 740 370',
            '2.Հաց',
            '1905/1234567 1Հտ 300 300',
          ].join('\n'),
          0,
        ),
        rowsOf(
          ['3.Պանիր Լոռի', '0406/1122334 1Հտ 2100 2100', rule, 'Ընդամենը 3140.00'].join('\n'),
          1,
        ),
      ]),
    )
    expect(got.lines.map((line) => line.printed)).toEqual(['Կաթ', 'Հաց', 'Պանիր Լոռի'])
    expect(got.balanced).toBe(true)
  })
})

// Review round 7 of MOL-125.
describe('a part that starts at an item’s figures, its name left in the part before (review Р26)', () => {
  const rows = (am05 as Fixture).readings[0]!.replace('0403/1160033', '0403/1160035').split('\n')
  const name = rows.findIndex((row) => row.startsWith('9.Յոգուրտ'))
  const figures = rows.findIndex((row) => row.startsWith('0403/1160036'))
  const join = (part1: readonly string[], part2: readonly string[]) =>
    parseReceiptText(mergeParts([rowsOf(part1.join('\n'), 0), rowsOf(part2.join('\n'), 1)]))
  const whole = parse(rows.join('\n')).lines.map((line) => line.sku)

  it('keeps the neighbour one swap of OCR off when the cut falls between its name and figures', () => {
    expect(join(rows.slice(0, name + 1), rows.slice(figures)).lines.map((l) => l.sku)).toEqual(
      whole,
    )
  })

  it('keeps it when the next part lost the name at its edge and there is no overlap', () => {
    expect(join(rows.slice(0, name), rows.slice(figures)).lines.map((l) => l.sku)).toEqual(
      expect.arrayContaining(['1160035', '1160036']),
    )
  })
})

// Review round 8 of MOL-125.
describe('an item read twice at a seam, its article one swap of OCR off (review Р27)', () => {
  it('is not balanced away silently: the line the total changed to make up for it is highlighted', () => {
    const rows = (am05 as Fixture).readings[1]!.split('\n')
    const figures = rows.findIndex((row) => row.startsWith('0403/1160036'))
    const got = parseReceiptText(
      mergeParts([
        rowsOf(rows.slice(0, figures + 1).join('\n'), 0),
        rowsOf(
          [
            (rows[figures] ?? '').replace('0403/1160036', '0403/1160086'),
            ...rows.slice(figures + 1),
          ].join('\n'),
          1,
        ),
      ]),
    )
    const whole = parseReceiptText(rowsOf(rows.join('\n'), 0))
    const wrong = got.lines.filter((line) => {
      const same = whole.lines.find((w) => w.sku === line.sku)
      return same?.sumHundredths !== line.sumHundredths
    })
    expect(wrong.length).toBeGreaterThan(0)
    expect(!got.balanced || wrong.every((line) => !line.settled)).toBe(true)
  })
})

// Review round 9 of MOL-125.
describe('two flavours at one price numbered …5 and …6 in one photo (review Р28)', () => {
  it('are read right and neither is highlighted: there is no seam to read one twice', () => {
    const read = bestReading(
      (am05 as Fixture).readings.map((text) =>
        rowsOf(text.replace('0403/1160033', '0403/1160035'), 0),
      ),
    )
    const yoghurts = read.lines.filter((line) => line.sku === '1160035' || line.sku === '1160036')
    expect(yoghurts.map((line) => [line.sumHundredths, line.settled])).toEqual([
      [29_000, true],
      [29_000, true],
    ])
  })
})

// MOL-226: KFC's receipt in its two prints — the till's table and the fiscal terminal's — as Tesseract
// read them, under a made-up head (`.scratch/tasks/status/MOL-226/fixtures.mts`). Eight dishes of
// class 56.10; the total 8 510.
describe('a fiscal till read by its class code (MOL-226)', () => {
  const kfc = (fixture: { readings: string[] }) =>
    bestReading(fixture.readings.map((text) => rowsOf(text, 0)))
  const SUMS = [68_809, 393_191, 12_000, 48_032, 62_441, 11_527, 130_000, 125_000]

  it('reads the till’s table: code, article and figures on a row, the name under it', () => {
    const got = kfc(am14)
    expect([got.layout, got.balanced, got.totalHundredths]).toEqual(['class', true, 851_000])
    expect(got.lines.map((l) => l.sumHundredths)).toEqual(SUMS)
    expect(got.lines.every((l) => l.quantityMilli === 1_000 && l.unit === 'piece')).toBe(true)
    // the fourth line's code OCR lost: no article, and the receipt's one class of services (review А1b)
    expect(got.lines.every((l) => l.hs === '56.10')).toBe(true)
    expect(got.lines.map((l) => l.sku)).toEqual([
      '745030',
      '771300',
      '740080',
      null,
      '770550',
      '740000',
      '750080',
      '755009',
    ])
    expect(got.lines.map((l) => l.printed)).toEqual([
      'Ֆրի ստանդարտ',
      '16 Թն',
      'Պանրային սոուս',
      'Տա Ֆրի ստանդարտ',
      '2 Ստրիպս',
      'Կետչուպ',
      'Չիզբուրգեր դե լյուքս Օրիգինալ',
      // the name OCR lost: the line stays, its name is the person’s to give
      '',
    ])
    expect([got.tin, got.date, got.time, got.receiptNo]).toEqual([
      '01234567',
      '2026-10-01',
      '12:00',
      '12345678',
    ])
  })

  it('reads the terminal’s print: the code, the name, then price × count = sum, no article', () => {
    const got = kfc(am14t)
    expect([got.layout, got.balanced, got.totalHundredths]).toEqual(['class', true, 851_000])
    expect(got.lines.map((l) => l.sumHundredths)).toEqual(SUMS)
    expect(got.lines.every((l) => l.hs === '56.10' && l.sku === null)).toBe(true)
    expect(got.lines.map((l) => l.printed)).toContain('Թթվիսթեր')
    // the terminal's head as OCR lost it: nothing is made up of it
    expect([got.tin, got.date, got.time, got.receiptNo]).toEqual([null, null, null, null])
  })

  it('cuts out the row of figures only', () => {
    const got = kfc(am14)
    expect(got.lines.every((l) => l.rows.length === 1 && /\d/.test(l.rows[0]!.text))).toBe(true)
  })

  const receipt = (...texts: string[]) => parseReceiptText(rowsOf(texts.join('\n'), 0))

  it('puts back the point OCR lost in a terminal’s sum: «393191դրամ» is 3 931.91', () => {
    const got = receipt('Դաս՝ 56.10', '16 Թև', '3931.91x1.0 հատ=393191դրամ', 'Ընդամենը 3931.91')
    expect(
      got.lines.map((l) => [l.quantityMilli, l.priceHundredths, l.sumHundredths, l.settled]),
    ).toEqual([[1_000, 393_191, 393_191, true]])
    expect(got.balanced).toBe(true)
  })

  it('reads «=» as OCR prints it, «-», and a count with its point lost, «x10» for 1.0', () => {
    const line = receipt('Դաս՝ 56.10', 'Ֆրի', '688 09х10 հստ-688.09դրամ').lines[0]!
    expect([line.quantityMilli, line.priceHundredths, line.sumHundredths, line.settled]).toEqual([
      1_000,
      68_809,
      68_809,
      true,
    ])
  })

  it('undoes a count OCR misread by the arithmetic: «4 հատ 688.09 688.09» is one', () => {
    const line = receipt('Դաս. 56.10, Ն/Կ 745030 4 հատ 688.09 688.09', 'Ֆրի').lines[0]!
    expect([line.quantityMilli, line.sumHundredths, line.sku, line.settled]).toEqual([
      1_000,
      68_809,
      '745030',
      true,
    ])
  })

  it('puts back the point of a till’s price by its sum: «11527 115.27»', () => {
    const line = receipt('Դաս. 56.10, Ն/Կ 740000 1հատ 11527 115.27', 'Կետչուպ').lines[0]!
    expect([line.priceHundredths, line.sumHundredths, line.printed]).toEqual([
      11_527,
      11_527,
      'Կետչուպ',
    ])
  })

  it('takes a name on the figures’ row and the row under it', () => {
    const got = receipt(
      'Դաս. 56.10, Ն/Կ 750080',
      'Չիզբուրգեր դե լյուքս 1 հատ 1300 1300',
      'Օրիգինալ',
      'Դաս. 56.10, Ն/Կ 755000 1 հատ 1250 1250',
      'Թվիստեր',
    )
    expect(got.lines.map((l) => [l.printed, l.sumHundredths])).toEqual([
      ['Չիզբուրգեր դե լյուքս Օրիգինալ', 130_000],
      ['Թվիստեր', 125_000],
    ])
  })

  it('takes the name above the figures where the terminal prints it, in two rows', () => {
    const got = receipt(
      'Դաս՝ 56.10',
      'Չիզբուրգեր դե լյուքս Օրիգի',
      'նալ',
      '1300.0x1.0 հատ=1300.00դրամ',
      'Դաս՝ 56.10',
      'Թվիստեր',
      '1250.0x1.0 հատ=1250.00դրամ',
    )
    expect(got.lines.map((l) => l.printed)).toEqual(['Չիզբուրգեր դե լյուքս Օրիգի նալ', 'Թվիստեր'])
  })

  it('keeps a row of figures whose code OCR lost, of the receipt’s one class of services', () => {
    const got = receipt(
      'Դաս. 56.10, Ն/Կ 745030 1հատ 688.09 688.09',
      'Ֆրի ստանդարտ',
      'Ан Ц 56. յ wit 70211',
      'lee pt Me TAAL 1հատ 480.32 480.32',
      'Ֆրի ստանդարտ',
      'Ընդամենը 1168.41',
    )
    expect(got.lines.map((l) => [l.hs, l.sumHundredths, l.printed])).toEqual([
      ['56.10', 68_809, 'Ֆրի ստանդարտ'],
      // a smudge of Latin on the figures' row is no name beside the Armenian under it
      ['56.10', 48_032, 'Ֆրի ստանդարտ'],
    ])
    expect(got.balanced).toBe(true)
  })

  it('knows the receipt’s class read without its point: «Դաս. 5610», «нии‘ 5610»', () => {
    const got = receipt(
      'Դաս՝ 56.10',
      'Ֆրի',
      '120.0x1.0 հատ=120.00դրամ',
      'Դաս. 5610',
      '2 Ստրիպս',
      '624.41x1.0 հատ=624.41դրամ',
      'нии‘ 5610',
      'Կետչուպ',
      '115.27x1.0 հատ=115.27դրամ',
    )
    expect(got.lines.map((l) => [l.hs, l.printed])).toEqual([
      ['56.10', 'Ֆրի'],
      ['56.10', '2 Ստրիպս'],
      ['56.10', 'Կետչուպ'],
    ])
  })

  it('keeps a customs heading of goods as it is: «Դաս. 0401»', () => {
    const line = receipt('Դաս. 0401, Ն/Կ 1163909 1հատ 370 370', 'Կաթ').lines[0]!
    expect([line.hs, line.sku, line.sumHundredths]).toEqual(['0401', '1163909', 37_000])
  })

  it('weighs a line in kilograms', () => {
    const line = receipt('Դաս՝ 0406', 'Պանիր', '1290.00x0.742 կգ=957.18դրամ').lines[0]!
    expect([line.unit, line.quantityMilli, line.priceHundredths, line.sumHundredths]).toEqual([
      'kg',
      742,
      129_000,
      95_718,
    ])
  })

  it('keeps a line whose price OCR lost at its sum, unsettled', () => {
    const line = receipt('Դաս. 56.10. Ն/Կ 740080', 'Պանրային սոուս 1 հատ Ա 120').lines[0]!
    expect([line.sumHundredths, line.settled]).toEqual([12_000, false])
  })

  it('finds no item in the head above the first code or after the total', () => {
    const got = receipt(
      'ՀՎՀՀ: 01234567',
      'ՍՀ: 00012345678',
      'ԿՀ: 12345',
      'Բաժին 1.2',
      '/ Շրջ.հարկ /:8510 2 8510',
      'Դաս. 56.10, Ն/Կ 745030 1հատ 688.09 688.09',
      'Ֆրի',
      'Հսկիչ նշանի քանակ 0',
      'Ընդամենը 688.09',
      'Վճարված Անկանխիկ 688.09 688.09',
    )
    expect(got.lines.map((l) => l.sumHundredths)).toEqual([68_809])
    expect(got.balanced).toBe(true)
  })

  it('finds no line on a receipt of a section with no items and no class code', () => {
    // a sole trader's terminal (am-15…am-24 of the bench): «Բաժին 1» and a turnover tax, no item
    const got = receipt(
      'ՀՎՀՀ 01234567',
      'Բաժին 1',
      'Շրջանառության հարկ 1700 1700',
      'Ընդամենը 1700.00',
      'Անկանխիկ 1700.00 1700.00',
    )
    expect(got.lines).toEqual([])
  })

  it('leaves a receipt both layouts read to them: a card with no class code', () => {
    expect(read(am01 as Fixture).layout).toBe('card')
    expect(read(am04 as Fixture).layout).toBe('table')
  })

  it('reads four hundred coded rows of junk within the ceilings', () => {
    const rows = Array.from({ length: 400 }, (_, i) =>
      i % 2 === 0 ? `Դաս. 56.10, Ն/Կ 7${String(i).padStart(5, '0')} 4 հատ 1388.89 1883.44` : 'Ֆրի',
    )
    const started = performance.now()
    const got = receipt(...rows, 'Ընդամենը 99999.99')
    expect(got.lines).toHaveLength(200)
    expect(performance.now() - started).toBeLessThan(5_000)
  })
})

// MOL-226, review round 1: what OCR does to the class reading that the first version lost.
describe('a fiscal till read by its class code: what OCR does (MOL-226, review)', () => {
  const kfc = (readings: readonly string[]) => bestReading(readings.map((text) => rowsOf(text, 0)))
  const receipt = (...texts: string[]) => parseReceiptText(rowsOf(texts.join('\n'), 0))

  it('gives a line whose code OCR lost the receipt’s one class of services, and no other (А1b)', () => {
    const dishes = receipt(
      'Դաս. 56.10, Ն/Կ 745030 1հատ 688.09 688.09',
      'Ֆրի',
      'Ан Ц 56. յ wit 70211',
      'lee pt 1հատ 120.00 120.00',
      'Պանրային սոուս',
    )
    expect(dishes.lines.map((l) => [l.hs, l.sku])).toEqual([
      ['56.10', '745030'],
      ['56.10', null],
    ])
    // two headings of goods: a lost code is not made up
    const goods = receipt(
      'Դաս. 0401, Ն/Կ 1163909 1հատ 370 370',
      'Կաթ',
      'Դաս. 1905, Ն/Կ 1163910 1հատ 250 250',
      'Թխվածքաբլիթ',
      'lee pt 1հատ 120.00 120.00',
      'Սոուս',
    )
    expect(goods.lines.map((l) => l.hs)).toEqual(['0401', '1905', null])
  })

  it('keeps the first item whose code row OCR lost whole, on the till’s print (А2)', () => {
    const lost = am14.readings.map((text) =>
      text.replace(
        /^.*(?:ՆԿ 15030|Ն\/Կ 745030).*$/m,
        'Ан Ц 56. յ wit 70211\nlee pt 4 հատ 688.09 688.09',
      ),
    )
    const got = kfc(lost)
    expect(got.lines).toHaveLength(8)
    expect(got.lines[0]?.sumHundredths).toBe(68_809)
    expect(got.balanced).toBe(true)
  })

  it('keeps the first dish whose «Դաս» OCR read «հա ‘5б.10», on the terminal’s print (А2)', () => {
    const got = kfc(am14t.readings.map((text) => text.replace('հաս ‘56.10', 'հա ‘5б.10')))
    expect(got.lines).toHaveLength(8)
    expect(got.balanced).toBe(true)
  })

  it('takes no figures of the head above the first code for an item', () => {
    const got = receipt(
      'Բաժին 1.2',
      '/ Շրջ.հարկ /:8510 8510',
      'Որից ԱՍՀ՝ = 0.00',
      'Դաս՝ 56.10',
      'Ֆրի',
      '688.09x1.0 հատ=688.09դրամ',
      'Ընդամենը 688.09',
    )
    expect(got.lines.map((l) => l.sumHundredths)).toEqual([68_809])
  })

  it('reads «հատ» misread «հաս» after a count as a unit, never a code (А3)', () => {
    const till = receipt(
      'Դաս. 56.10, Ն/Կ 750080',
      'Չիզբուրգեր դե լյուքս 1 հաս 1300 1300',
      'Օրիգինալ',
      'Դաս. 56.10, Ն/Կ 755009 1 հատ 1250 1250',
      'Թվիստեր',
      'Ընդամենը 2550',
    )
    expect([till.lines.map((l) => l.sumHundredths), till.balanced]).toEqual([
      [130_000, 125_000],
      true,
    ])
    const terminal = receipt(
      'Դաս՝ 56.10',
      'Չիզբուրգեր',
      '1300.0x1.0 հաս=1300.00դրամ',
      'Դաս՝ 56.10',
      'Թվիստեր',
      '1250.0x1.0 հատ=1250.00դրամ',
      'Ընդամենը 2550.00',
    )
    expect(terminal.lines.map((l) => l.sumHundredths)).toEqual([130_000, 125_000])
  })

  it('reads a price that begins with the receipt’s class as a price: «5610.00x1.0» (А4)', () => {
    const got = receipt(
      'Դաս՝ 56.10',
      'Բաքեթ',
      '5610.00x1.0 հատ=5610.00դրամ',
      'Դաս՝ 56.10',
      'Թվիստեր',
      '1250.0x1.0 հատ=1250.00դրամ',
      'Ընդամենը 6860.00',
    )
    expect(got.lines.map((l) => [l.printed, l.sumHundredths, l.settled])).toEqual([
      ['Բաքեթ', 561_000, true],
      ['Թվիստեր', 125_000, true],
    ])
  })

  it('reads a name ending in «աս» with a volume as a name: «Կվաս 1000մլ» (А5)', () => {
    const got = receipt(
      'Դաս՝ 56.10',
      'Կվաս 1000մլ',
      '500.00x1.0 հատ=500.00դրամ',
      'Դաս՝ 56.10',
      'Թվիստեր',
      '1250.0x1.0 հատ=1250.00դրամ',
    )
    expect(got.lines.map((l) => [l.printed, l.hs])).toEqual([
      ['Կվաս 1000մլ', '56.10'],
      ['Թվիստեր', '56.10'],
    ])
  })
})

// MOL-226, review round 2: «աս» is the word «Դաս» only, and a class is no figure that goes on.
describe('a fiscal till read by its class code: the code’s mark (MOL-226, review 2)', () => {
  const kfc = (readings: readonly string[]) => bestReading(readings.map((text) => rowsOf(text, 0)))
  const receipt = (...texts: string[]) => parseReceiptText(rowsOf(texts.join('\n'), 0))

  it('names the terminal’s first dish whose code row OCR lost whole (Б1)', () => {
    const got = kfc(am14t.readings.map((text) => text.replace(/հաս ‘56.10\n/, '')))
    expect(got.lines).toHaveLength(8)
    expect(got.lines[0]).toMatchObject({ sumHundredths: 68_809, printed: 'Ֆրի ստանդարտ' })
  })

  it('reads a price that begins with the class as a price in every form (Б2)', () => {
    const terminal = receipt(
      'Դաս՝ 56.10',
      'Բաքեթ',
      '5610 00х10 հստ-5610.00դրամ',
      'Դաս՝ 56.10',
      'Թվիստեր',
      '1250.0x1.0 հատ=1250.00դրամ',
      'Ընդամենը 6860.00',
    )
    expect(terminal.lines.map((l) => [l.printed, l.sumHundredths, l.settled])).toEqual([
      ['Բաքեթ', 561_000, true],
      ['Թվիստեր', 125_000, true],
    ])
    const till = receipt(
      'Դաս. 56.10, Ն/Կ 745031',
      'Բաքեթ 5610 5610',
      'Դաս. 56.10, Ն/Կ 745032 1հատ 120.00 120.00',
      'Սոուս',
      'Ընդամենը 5730',
    )
    expect([till.lines.map((l) => l.sumHundredths), till.balanced]).toEqual([
      [561_000, 12_000],
      true,
    ])
  })

  it('never reads «աս» inside a name as «Դաս»: «Կվաս 1000 մլ», «Կվաս 1000» (Б3)', () => {
    // a bare number at the row's end is no part of a name: it reads as a till's figure would
    for (const [name, printed] of [
      ['Կվաս 1000 մլ', 'Կվաս 1000 մլ'],
      ['Կվաս 1000', 'Կվաս'],
      ['Անանաս 1500 գ', 'Անանաս 1500 գ'],
    ] as const) {
      const got = receipt(
        'Դաս՝ 56.10',
        name,
        '500.00x1.0 հատ=500.00դրամ',
        'Դաս՝ 56.10',
        'Թվիստեր',
        '1250.0x1.0 հատ=1250.00դրամ',
      )
      expect(got.lines.map((l) => [l.printed, l.hs])).toEqual([
        [printed, '56.10'],
        ['Թվիստեր', '56.10'],
      ])
    }
  })

  it('reads a code glued to its article, OCR having eaten the comma (Б4)', () => {
    const dish = receipt(
      'Դաս. 56.10Ն/Կ 745030 1հատ 688.09 688.09',
      'Ֆրի',
      'Դաս. 56.10, Ն/Կ 745031 1հատ 120.00 120.00',
      'Սոուս',
    )
    expect(dish.lines[0]).toMatchObject({ hs: '56.10', sku: '745030', printed: 'Ֆրի' })
    const goods = receipt(
      'Դաս. 0401Ն/Կ 1163909 1հատ 370 370',
      'Կաթ',
      'Դաս. 1905, Ն/Կ 1163910 1հատ 250 250',
      'Հաց',
    )
    expect(goods.lines[0]).toMatchObject({ hs: '0401', sku: '1163909', printed: 'Կաթ' })
  })

  it('reads «հաս» before two amounts as a unit whatever OCR made of the count (Б5)', () => {
    const got = receipt(
      'Դաս. 56.10, Ն/Կ 750080',
      'Չիզբուրգեր դե լյուքս | հաս 1300 1300',
      'Օրիգինալ',
      'Դաս. 56.10, Ն/Կ 755009 1 հատ 1250 1250',
      'Թվիստեր',
      'Ընդամենը 2550',
    )
    expect([got.lines.map((l) => l.sumHundredths), got.balanced]).toEqual([
      [130_000, 125_000],
      true,
    ])
  })
})

// MOL-226, review round 3: an amount is not a count, a price is not an article, the head is not a name.
describe('a fiscal till read by its class code: counts, articles, the head (MOL-226, review 3)', () => {
  const receipt = (...texts: string[]) => parseReceiptText(rowsOf(texts.join('\n'), 0))

  it('reads a till with no article whose count stands apart from «հատ» (В1)', () => {
    const dishes = receipt(
      'Դաս. 56.10 1 հատ 1250 1250',
      'Թվիստեր',
      'Դաս. 56.10 1 հատ 1300 1300',
      'Չիզբուրգեր',
      'Ընդամենը 2550',
    )
    expect([dishes.lines.map((l) => [l.hs, l.sumHundredths]), dishes.balanced]).toEqual([
      [
        ['56.10', 125_000],
        ['56.10', 130_000],
      ],
      true,
    ])
    const goods = receipt(
      'Դաս. 0401 2 հատ 370 740',
      'Կաթ',
      'Դաս. 1905 1 հատ 250 250',
      'Թխվածքաբլիթ',
      'Ընդամենը 990',
    )
    expect(goods.lines.map((l) => [l.hs, l.quantityMilli, l.sumHundredths])).toEqual([
      ['0401', 2_000, 74_000],
      ['1905', 1_000, 25_000],
    ])
  })

  it('makes no line of a stray digit after the terminal’s code (В2)', () => {
    const got = receipt(
      'Դաս՝ 56.10',
      'Ֆրի',
      '688.09x1.0 հատ=688.09դրամ',
      'Դաս՝ 56.10 1',
      'Թվիստեր',
      '1250.0x1.0 հատ=1250.00դրամ',
      'Ընդամենը 1938.09',
    )
    expect(got.lines.map((l) => [l.printed, l.sumHundredths, l.settled])).toEqual([
      ['Ֆրի', 68_809, true],
      ['Թվիստեր', 125_000, true],
    ])
  })

  it('reads an article glued to the code with its comma: «56.10,745030» (№ 9)', () => {
    const line = receipt('Դաս. 56.10,745030 1հատ 688.09 688.09', 'Ֆրի').lines[0]
    expect(line).toMatchObject({ hs: '56.10', sku: '745030', printed: 'Ֆրի' })
  })

  it('reads «Դաս» with a letter OCR glued before it: «րԴաս. 0401» (В3)', () => {
    const line = receipt(
      'րԴաս. 0401, Ն/Կ 1163909 1հատ 370 370',
      'Կաթ',
      'Դաս. 1905, Ն/Կ 1163910 1հատ 250 250',
      'Հաց',
    ).lines[0]
    expect(line).toMatchObject({ hs: '0401', sku: '1163909', printed: 'Կաթ' })
  })

  const first = (...above: string[]) =>
    receipt(
      '«ՖԱՍՏՖՈՒԴ»',
      ...above,
      '1300.0x1.0 հատ=1300.00դրամ',
      'Դաս՝ 56.10',
      'Թվիստեր',
      '1250.0x1.0 հատ=1250.00դրամ',
      'Ընդամենը 2550.00',
    ).lines[0]?.printed

  it('names the terminal’s first dish whose code OCR lost by its rows, never the head’s (В4, № 11)', () => {
    expect(first('/շրջ հարկ/ = 851000', 'Չիզբուրգեր', 'դե լյուքս', 'Օրիգինալ')).toBe(
      'Չիզբուրգեր դե լյուքս Օրիգինալ',
    )
    expect(first('/շրջ հարկ/ = 851000', 'ՖԻՍԿԱԼ ԿՏՐՈՆ', 'Ֆրի')).toBe('Ֆրի')
    expect(first('ԳՅՈՒՄՐԻ', 'Պանրային սոուս')).toBe('Պանրային սոուս')
    // the cashier's name is nobody's dish: it would go into the shared catalogue
    expect(first('Գանձապահ Արամ', 'Պանրային սոուս')).toBe('Պանրային սոուս')
  })

  it('keeps no number before a one-letter smudge in a name: «Ֆրի ստանդարտ 2 Ա» (№ 12)', () => {
    const line = receipt('Դաս. 56.10, Ն/Կ 745030 1հատ 688.09 688.09', 'Ֆրի ստանդարտ 2 Ա').lines[0]
    expect(line?.printed).toBe('Ֆրի ստանդարտ')
  })
})

// MOL-226, review round 4: junk after a code is junk, «Դ» has look-alikes, a name runs on, capitals.
describe('a fiscal till read by its class code: junk, look-alikes, the first name (MOL-226, review 4)', () => {
  const receipt = (...texts: string[]) => parseReceiptText(rowsOf(texts.join('\n'), 0))

  it('makes no line of digits of junk after the terminal’s code, one or two (Г1)', () => {
    for (const code of ['Դաս՝ 56.10 1', 'Դաս՝ 56.10 19', 'Դաս՝ 56.10 20-']) {
      const got = receipt(
        'Դաս՝ 56.10',
        'Ֆրի',
        '688.09x1.0 հատ=688.09դրամ',
        code,
        'Թվիստեր',
        '1250.0x1.0 հատ=1250.00դրամ',
        'Ընդամենը 1938.09',
      )
      expect(got.lines.map((l) => [l.printed, l.sumHundredths, l.settled])).toEqual([
        ['Ֆրի', 68_809, true],
        ['Թվիստեր', 125_000, true],
      ])
    }
  })

  it('reads «Դ» misread as «Գ» or «Ղ» on every code (№ 13)', () => {
    const got = receipt(
      'Գաս. 56.10, Ն/Կ 745030 1հատ 688.09 688.09',
      'Ֆրի',
      'Ղաս. 56.10, Ն/Կ 745031 1հատ 120 120',
      'Սոուս',
      'Ընդամենը 808.09',
    )
    expect([got.lines.map((l) => [l.hs, l.sku]), got.balanced]).toEqual([
      [
        ['56.10', '745030'],
        ['56.10', '745031'],
      ],
      true,
    ])
  })

  const first = (...above: string[]) =>
    receipt(
      '«ՖԱՍՏՖՈՒԴ»',
      '/շրջ հարկ/ = 851000',
      ...above,
      '1300.0x1.0 հատ=1300.00դրամ',
      'Դաս՝ 56.10',
      'Թվիստեր',
      '1250.0x1.0 հատ=1250.00դրամ',
    ).lines[0]?.printed

  it('takes a row over the first dish’s name only where the name runs on (№ 14)', () => {
    expect(first('Շնորհակալություն', 'Պանրային սոուս')).toBe('Պանրային սոուս')
    expect(first('Չիզբուրգեր դե լյուքս Օրիգի', 'նալ')).toBe('Չիզբուրգեր դե լյուքս Օրիգի նալ')
  })

  it('names the first dish in capitals on a till that names in capitals (Г2)', () => {
    const got = receipt(
      '«ՖԱՍՏՖՈՒԴ»',
      '/շրջ հարկ/ = 851000',
      'ԵՐԵՎԱՆ ՍԵՆԴՎԻՉ',
      '688.09x1.0 հատ=688.09դրամ',
      'Դաս՝ 56.10',
      'ԹՎԻՍՏԵՐ',
      '1250.0x1.0 հատ=1250.00դրամ',
    )
    expect(got.lines.map((l) => l.printed)).toEqual(['ԵՐԵՎԱՆ ՍԵՆԴՎԻՉ', 'ԹՎԻՍՏԵՐ'])
  })
})

// MOL-226, review round 5: with no «Դաս», a class followed by a line's figures is a price, whatever form.
describe('a fiscal till read by its class code: a price that begins with the class (MOL-226, review 5)', () => {
  const receipt = (...texts: string[]) => parseReceiptText(rowsOf(texts.join('\n'), 0))

  it('reads the till’s price as a price, its sum misread or of two pieces (Д1, № 16)', () => {
    for (const [figures, total, sum] of [
      // the total puts back the sum OCR misread: 5 730 is 5 610 and 120
      ['5610 5640', '5730', 561_000],
      ['5610 11220', '11340', 1_122_000],
    ] as const) {
      const got = receipt(
        'Դաս. 56.10, Ն/Կ 745031',
        `Բաքեթ ${figures}`,
        'Դաս. 56.10, Ն/Կ 745032 1հատ 120.00 120.00',
        'Սոուս',
        `Ընդամենը ${total}`,
      )
      expect(got.lines.map((l) => l.printed)).toEqual(['Բաքեթ', 'Սոուս'])
      expect(got.lines[0]?.sumHundredths).toBe(sum)
    }
  })

  it('reads the terminal’s price whose «x» OCR read «:» (Д2)', () => {
    for (const figures of ['5610:1.0 հատ-5610.00դրամ', '5610 00:1.0 հատ-5610.00դրամ']) {
      const line = receipt(
        'Դաս՝ 56.10',
        'Բաքեթ',
        figures,
        'Դաս՝ 56.10',
        'Թվիստեր',
        '1250.0x1.0 հատ=1250.00դրամ',
      ).lines[0]
      expect(line).toMatchObject({ printed: 'Բաքեթ', sumHundredths: 561_000, settled: true })
    }
  })

  it('keeps the article’s mark and the code’s junk out of a name, the article read (№ 15)', () => {
    const lost = receipt('Դաս. 56.10, Ն/Կ 1հատ 688.09 688.09', 'Ֆրի').lines[0]
    expect(lost).toMatchObject({ printed: 'Ֆրի', sku: null })
    const junk = receipt('Դաս. 56.10 19 Ն/Կ 745030 1հատ 688.09 688.09', 'Ֆրի').lines[0]
    expect(junk).toMatchObject({ printed: 'Ֆրի', sku: '745030' })
  })

  it('still reads a code with no «Դաս» on its own row, or before its article', () => {
    const got = receipt(
      'Դաս. 56.10, Ն/Կ 745030 1հատ 688.09 688.09',
      'Ֆրի',
      'ամ. 56.10, Li 740000 1հատ 11527 115.27',
      'Կետչուպ',
      'Ջ ւս 56 10',
      'Թվիստեր 1 հատ 1250 1250',
    )
    expect(got.lines.map((l) => [l.hs, l.sku, l.sumHundredths])).toEqual([
      ['56.10', '745030', 68_809],
      ['56.10', '740000', 11_527],
      ['56.10', null, 125_000],
    ])
  })
})

// MOL-226, review round 6: a code read with no «Դաս» is followed by what follows a code with it.
describe('a fiscal till read by its class code: a code with no «Դաս» (MOL-226, review 6)', () => {
  const receipt = (...texts: string[]) => parseReceiptText(rowsOf(texts.join('\n'), 0))

  it('takes junk after the terminal’s code with no «Դաս» for the code’s own (Е1)', () => {
    const got = receipt(
      'Դաս՝ 56.10',
      'Ֆրի',
      '688.09x1.0 հատ=688.09դրամ',
      'ши‘ 56 10 19',
      'Թվիստեր',
      '1250.0x1.0 հատ=1250.00դրամ',
      'Ընդամենը 1938.09',
    )
    expect(got.lines.map((l) => [l.printed, l.sumHundredths, l.settled])).toEqual([
      ['Ֆրի', 68_809, true],
      ['Թվիստեր', 125_000, true],
    ])
  })

  it('reads the till’s «ամ.» code with junk before its article, or with no article (Е2)', () => {
    for (const [code, sku] of [
      ['ամ. 56.10 19 Ն/Կ 745030', '745030'],
      ['ամ. 56.10', null],
    ] as const) {
      const line = receipt(
        'Դաս. 56.10, Ն/Կ 745031 1հատ 120.00 120.00',
        'Սոուս',
        `${code} 1հատ 688.09 688.09`,
        'Ֆրի ստանդարտ',
        'Ընդամենը 808.09',
      ).lines[1]
      expect(line).toMatchObject({
        hs: '56.10',
        sku,
        printed: 'Ֆրի ստանդարտ',
        sumHundredths: 68_809,
      })
    }
  })
})

describe('a section with no items: a sole trader’s receipt (MOL-227)', () => {
  // the forms are the bench's ten receipts of one sole trader (am-15…am-24), every name and number made up
  const reading = (...rows: string[]): TextRow[] =>
    rows.map((text, line) => ({ text, part: 0, line }))
  const bold = (tinWord: string, total: string, paid: string) =>
    reading(
      'ԽԱՆՈՒԹ ԱՁ',
      'ԳՅՈՒՄՐԻ Աբովյան 10',
      `${tinWord}: 12345678 Գ/Ը: 87654321`,
      'ՍԸ: NCC100000001',
      'ԿԸ: 00000049',
      '04-10-26 16:30:59 ԳԱՆՋԱՊԱԸ: 3',
      'Բաժին 1 - Բաժին 1',
      '/ Շրջանառության Ըարկ/ 1700.00',
      'Որից ԱԱԸ՝ 0.00',
      '(Ֆ)',
      `Ընդամենը' ${total}`,
      `Առձեռն ${paid}`,
      'ՖԻՍԿԱԼ ԸԱՄԱՐ 11223344',
    )

  it('reads the section whole: no line, the head of the terminal, the total all three print', () => {
    const got = bestReading([
      bold('СУСС', '1700.00', '1700.00'),
      bold('CUCC', '1700.00', '1700.00'),
    ])
    expect(got).toEqual({
      layout: 'department',
      tin: '12345678',
      date: '2026-10-04',
      time: '16:30',
      receiptNo: '11223344',
      totalHundredths: 170_000,
      balanced: false,
      lines: [],
    })
    expect(needsReshoot(got)).toBe(false)
  })

  it('never takes the receipt’s own number «ԿՀ: 00000049» for the tax number', () => {
    const got = bestReading([
      reading('ԿԸ: 00000049', 'Բաժին 1 - Բաժին 1', 'Ընդամենը 120.00', 'Առձեռն 120.00'),
    ])
    expect(got.layout).toBe('department')
    expect(got.tin).toBeNull()
  })

  it('takes the tax number after its word, a till number of as many digits never', () => {
    const got = bestReading([
      reading('ՀՎՀՀ 12345678 4/2 87654321', 'Բաժին 1', 'Ընդամենը 550.00', 'Առձեռն 550 00'),
    ])
    expect(got.tin).toBe('12345678')
    expect(got.totalHundredths).toBe(55_000)
  })

  it('outvotes a total OCR misread by the section and the payment (550.09 for 550.00)', () => {
    const got = bestReading([
      reading('Բաժին 1 1', 'py հարկ/ = 550 00', 'Ընդամենը 550.09', 'լոձեռն 550 00'),
    ])
    expect(got.totalHundredths).toBe(55_000)
  })

  it('reads no total one source alone gives: the thin print lost the point of the other two', () => {
    // am-20: «Կղդամեկը 18000», the section not read — the person types the total (Р-3)
    const got = bestReading([
      reading('ՀՎՀՀ 12345678 9/2 87654321', 'Ււսժին 1]', 'Կղդամեկը 18000', 'Бибби 1800 00'),
    ])
    expect(got.layout).toBe('department')
    expect(got.totalHundredths).toBeNull()
    expect(got.date).toBeNull()
  })

  it('reads no field the two readings read apart', () => {
    const got = bestReading([
      reading('CUCC: 87345678 9/С: 87654321', '04-10-26 16:30:59', 'Բաժին 1', 'Ընդամենը 1700.00'),
      reading('СУСС: 12345678 Գ/Ը: 87654321', '04-10-26 16:31:59', 'Բաժին 1', 'Առձեռն 1700.00'),
    ])
    expect(got.tin).toBeNull()
    expect(got.date).toBe('2026-10-04')
    expect(got.time).toBeNull()
    expect(got.totalHundredths).toBe(170_000)
  })

  it('reads no total, time or number of two receipts on one photo (am-21)', () => {
    const got = bestReading([
      reading(
        '57311783 Գ/1',
        '04-10-26 14:23:15 ԳԱՆՔԱՊԱԼ: 3',
        'Բաժին 1 - Բաժին 1 :',
        'Շրջանառության Լարկ/ 3660.00',
        '3660.00',
        'СУСС: 12345678 Գ/Ը: 87654321',
        '04-10-26 14:27:34 ԳԱՆՋԱՊԱԸ: 3',
        'Բաժին 1 - Բաժին 1',
        '/ Շրջանառության Ըարկ/ 1200.00',
        'Ընդամենը՝ 1200.00',
        'Առձեռն 1200.00',
        'ՖԻՍԿԱԼ ԸԱՄԱՐ 11223344',
      ),
    ])
    expect(got.layout).toBe('department')
    expect([got.totalHundredths, got.time, got.receiptNo]).toEqual([null, null, null])
    expect(got.date).toBe('2026-10-04')
  })

  it('must not fire where an item’s mark is read: Dog City and KFC print «Բաժին» over their items', () => {
    const dogCity = bestReading([
      reading(
        'Բաժին 1',
        '| (3824) ՏՈՖՈՒ',
        '| 1|ԴԵՂՉ ваши) 1 2 200',
        'Ընդամենը: 9450.00',
        'Կանխիկ 9450.00',
      ),
    ])
    const kfc = bestReading([
      reading('Բաժին 1-1', '/շրջ հարկ/ = 8510 00', 'Դաս՝ 56.10', 'Ֆրի', 'Ընդամենը 8510.00'),
    ])
    for (const got of [dogCity, kfc]) {
      expect(got.layout).not.toBe('department')
    }
  })

  it('must not fire on a receipt with items whose lines OCR lost and no section is printed', () => {
    const got = bestReading([reading('ԵՐԵՎԱՆ ՍԻԹԻ', 'ՀՎՀՀ 12345678', 'Ընդամենը 5460.00')])
    expect(got.layout).toBe('card')
    expect(needsReshoot(got)).toBe(true)
  })

  it('leaves a receipt that found a line to its layout, a section printed or not', () => {
    expect(read(am14t as Fixture).layout).toBe('class')
    expect(read(am04 as Fixture).layout).toBe('table')
  })
})
